Repository microsoft/azure-pipelines-agent, pull requests merged in 2020-08, with the labels that each got.

#3061 Support read-only default mounts
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.Listener/NuGet.Config
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Sdk/ContainerInfo.cs
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Agent.Worker/NuGet.Config
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
  src/Microsoft.VisualStudio.Services.Agent/NuGet.Config
  src/NuGet.Config
  src/Test/L0/Plugin/ChunkerTests.cs
  src/Test/NuGet.Config
Labels: enhancement

#3067 Retry Pipeline Artifact Uploads to prevent failing builds on transient errors
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactServer.cs
Labels: bug

#3069 Update dotnet-install script
  src/Misc/dotnet-install.ps1
Labels: internal

#3068 Localize "exiting..." string
  src/Agent.Listener/Agent.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: internal

#3077 Handle Workspace ID errors and update feature flag name
  src/Agent.Worker/ExecutionContext.cs
  src/Test/L1/Worker/ConfigL1Tests.cs
  src/Test/L1/Worker/L1TestBase.cs
Labels: bug

#3079 Fix null ref exceptions on artifact deletion jobs
  src/Agent.Listener/JobDispatcher.cs
Labels: bug

#3080 Throw an actionable error message for pipeline not found instead of object null reference
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV2.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: Area: Core, bug

#3084 Update dotnet-install.ps1
  src/Misc/dotnet-install.ps1
Labels: internal

#3083 Force Git to HTTP/1.1 as part of checkout
  src/Agent.Plugins/GitSourceProvider.cs
Labels: bug

#3064 added ability to suppress the error form unshelve command during getSource
  src/Agent.Plugins/ITfsVCCliManager.cs
  src/Agent.Plugins/TFCliManager.cs
  src/Agent.Plugins/TeeCliManager.cs
  src/Agent.Plugins/TfsVCCliManager.cs
  src/Agent.Plugins/TfsVCSourceProvider.cs
Labels: enhancement

#3089 Update the list of 3rd party dlls to sign
  .azure-pipelines/build-job.yml
  .azure-pipelines/signing.yml
  .vsts.release.yml
Labels: internal

#3092 Turn on Fetch By Commit For GitHub
  src/Agent.Plugins/GitSourceProvider.cs
Labels: Area: Core, enhancement

#3087 added retry to WorkfoldCloakAsync and WorkfoldCloakAsync
  src/Agent.Plugins/TFCliManager.cs
  src/Agent.Plugins/TeeCliManager.cs
Labels: enhancement

#3096 Limit container username to 32 characters
  src/Agent.Worker/ContainerOperationProvider.cs
Labels: misc
