Repository microsoft/azure-pipelines-agent, pull requests merged in 2020-05, with the labels that each got.

#2958 Default System.PreferGitFromPath to false
  src/Agent.Sdk/Knob/AgentKnobs.cs
Labels: bug

#2947 Add signature verification mode and support for multiple fingerprints
  src/Agent.Worker/SignatureService.cs
  src/Agent.Worker/TaskManager.cs
  src/Agent.Worker/TaskRunner.cs
  src/Microsoft.VisualStudio.Services.Agent/ConfigurationStore.cs
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L1/Worker/WorkerL1Tests.cs
Labels: enhancement

#2965 Fix ARM64 link in releaseNote.md
  releaseNote.md
Labels: bug

#2959 Added some additional, automated secrets maskers
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Knob/RuntimeKnobSource.cs
  src/Microsoft.VisualStudio.Services.Agent/AdditionalMaskingRegexes.CredScan.cs
  src/Microsoft.VisualStudio.Services.Agent/AdditionalMaskingRegexes.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Test/L0/HostContextL0.cs
  tools/CredScanRegexes/CredScanPatternExtractor.cs
  tools/CredScanRegexes/CredScanRegexes.csproj
  tools/CredScanRegexes/PatternProcessor.cs
  tools/CredScanRegexes/Program.cs
  tools/CredScanRegexes/nuget.config
  tools/CredScanRegexes/readme.md
Labels: enhancement

#2972 Retry TFVC Gets
  src/Agent.Plugins/TFCliManager.cs
  src/Agent.Plugins/TeeCliManager.cs
  src/Agent.Plugins/TfsVCCliManager.cs
Labels: enhancement

#2975 Add chunking tests to make sure all platforms work well in CI
  src/Test/L0/Plugin/ChunkerTests.cs
Labels: internal

#2977 Update vss-api-netcore to 0.5.151-private.
  src/Common.props
Labels: internal

#2976 Add ARM64 to server template
  src/Misc/InstallAgentPackage.template.xml
Labels: internal

#2981 Update vswhere to 2.8.4.
  src/Misc/externals.sh
Labels: enhancement

#2983 Using Execution context GetVariables instead of environment variable
  src/Agent.Worker/TestResults/Utils/TestResultUtils.cs
Labels: bug

#2987 Disable masking with the new regexes from CredScan
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Test/L0/HostContextL0.cs
Labels: bug
