Repository microsoft/azure-pipelines-agent, pull requests merged in 2020-03, with the labels that each got.

#2823 Ensure labels are added to prs
  .github/labelChecker/index.js
  .github/labelChecker/package-lock.json
  .github/labelChecker/package.json
  .github/workflows/labelChecker.yml
Labels: internal

#2833 Enable agent rollbacks
  src/Agent.Listener/SelfUpdater.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: misc

#2843 Updated to use mingit 2.25.1
  src/Misc/externals.sh
Labels: misc

#2819 Remove unneeded variables
  src/Agent.Worker/Release/ReleaseDirectoryManager.cs
Labels: internal

#2844 Fix multiline masking issue
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Test/L0/HostContextL0.cs
Labels: bug

#2848 More fixes for static analysis violations
  src/Agent.Listener/Agent.cs
  src/Agent.Plugins/PipelineArtifact/FileContainerProvider.cs
  src/Agent.Worker/AgentLogPlugin.cs
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/Release/Artifacts/BuildArtifact.cs
  src/Agent.Worker/Release/ContainerProvider/Helpers/ContainerProviderFactory.cs
  src/Agent.Worker/TestResults/TestDataPublisher.cs
  src/Microsoft.VisualStudio.Services.Agent/Logging.cs
  src/Test/L0/HostContextL0.cs
  src/Test/L0/Listener/AgentL0.cs
  src/Test/L0/Listener/Configuration/ConfigurationManagerL0.cs
  src/Test/L0/PagingLoggerL0.cs
  src/Test/L0/Worker/CodeCoverage/CodeCoverageCommandExtensionTests.cs
  src/Test/L0/Worker/ExecutionContextL0.cs
  src/Test/L0/Worker/JobExtensionL0.cs
  src/Test/L0/Worker/JobRunnerL0.cs
  src/Test/L0/Worker/TaskCommandExtensionL0.cs
  src/Test/L0/Worker/TaskManagerL0.cs
  src/Test/L0/Worker/Telemetry/TelemetryCommandExtensionTests.cs
  src/Test/L0/Worker/TestResults/ResultsCommandExtensionTests.cs
  src/dev.sh
  src/rules.ruleset
Labels: internal

#2851 Add scripts for querying pipelines that target retired images
  tools/FindPipelinesUsingRetiredImages/QueryJobHistoryForRetiredImages.ps1
  tools/FindPipelinesUsingRetiredImages/readme.md
Labels: misc

#2852 fix for Build.Repository.Name in multi-checkout scenario
  src/Agent.Sdk/Util/RepositoryUtil.cs
  src/Agent.Worker/Build/BuildJobExtension.cs
  src/Agent.Worker/Build/TrackingConfig.cs
  src/Test/L0/Util/RepositoryUtilL0.cs
Labels: bug

#2854 Bump releases arm timeout
  .vsts.release.yml
Labels: internal

#2859 Typo fix
  src/Agent.Plugins/PipelineCache/SavePipelineCacheV0.cs
Labels: misc

#2861 Fix issue where agent configuration errors out when trying to look up pool
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.Plugins/PipelineArtifact/FileContainerProvider.cs
  src/Agent.Worker/Build/FileContainerServer.cs
  src/Agent.Worker/Release/ReleaseJobExtension.cs
Labels: bug

#2809 Skip masking single space character secrets
  src/Agent.Worker/Worker.cs
Labels: misc

#2855 Add a warning message to Download Pipeline Artifact task
  src/Agent.Plugins/PipelineArtifact/FileContainerProvider.cs
  src/Agent.Plugins/PipelineArtifact/FileShareProvider.cs
  src/Agent.Plugins/PipelineArtifact/IArtifactProvider.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactProvider.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactServer.cs
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L0/Plugin/TestFileShareProvider/TestFileShareProviderL0.cs
Labels: enhancement

#2862 Knob for checkout verbosity
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Plugins/TfsVCSourceProvider.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/TaskPlugin.cs
Labels: internal

#2871 Don't unzip tasks for L1 tests
  src/Misc/externals.sh
  src/Test/L1/Mock/FakeTaskServer.cs
  src/Test/L1/Worker/L1TestBase.cs
Labels: internal

#2873 Add L1 tests for signing
  .vsts.template.windows.yml
  src/Misc/externals.sh
  src/Test/L1/Mock/FakeConfigurationStore.cs
  src/Test/L1/Worker/L1TestBase.cs
  src/Test/L1/Worker/WorkerL1Tests.cs
  src/dev.sh
Labels: internal

#2880 Sign 3rd party CommandLine.dll
  .azure-pipelines/signing.yml
Labels: enhancement

#2881 Add an ARM64 agent
  .vsts.ci.yml
  .vsts.release.yml
  assets.json
  releaseNote.md
  src/Agent.Listener/Program.cs
  src/Agent.PluginHost/Program.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/Program.cs
  src/Common.props
  src/Misc/externals.sh
  src/Misc/layoutbin/installdependencies.sh
  src/Misc/layoutroot/config.sh
  src/Test/L0/ConstantGenerationL0.cs
  src/dev.sh
  src/dir.proj
Labels: Area: Core, enhancement

#2882 include arm64 agent in releases
  .vsts.release.yml
Labels: internal

#2884 Pass the dryrun option through
  release/createReleaseBranch.js
Labels: internal
