Repository microsoft/azure-pipelines-agent, pull requests merged in 2020-09, with the labels that each got.

#3101 Fail if you can't connect to LocationService the first time
  src/Microsoft.VisualStudio.Services.Agent/LocationServer.cs
Labels: Area: Build, bug

#3105 Set ProvisioningState when creating an agent.
  src/Agent.Listener/Configuration/ConfigurationManager.cs
Labels: bug

#3103 Add Node 14 Handler
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/HandlerFactory.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/TaskManager.cs
  src/Agent.Worker/TaskRunner.cs
  src/Misc/externals.sh
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L0/NodeHandlerL0.cs
  src/Test/L0/Worker/TaskManagerL0.cs
Labels: enhancement

#3108 Added retries over WorkspaceNewAsync
  src/Agent.Plugins/TFCliManager.cs
Labels: enhancement

#3113 Sign node14
  .azure-pipelines/signing.yml
Labels: internal

#3115 Revert "Turn on Fetch By Commit For GitHub (#3092)"
  src/Agent.Plugins/GitSourceProvider.cs
Labels: bug

#3116 Don't set taskkey to read only
  src/Agent.Worker/ContainerOperationProvider.cs
Labels: internal

#3065 Extract a new zip every time for Tasks
  src/Agent.Listener/CommandLine/ConfigureAgent.cs
  src/Agent.Listener/CommandSettings.cs
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Worker/TaskManager.cs
  src/Microsoft.VisualStudio.Services.Agent/ConfigurationStore.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L0/Worker/TaskManagerL0.cs
Labels: Area: Core, enhancement

#3117 Switch to new HTTP handler by default
  src/Agent.Listener/Program.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Misc/layoutbin/installdependencies.sh
Labels: misc

#3114 Added retry for workfold unmap
  src/Agent.Plugins/TFCliManager.cs
Labels: enhancement

#3122 Fix node existence check
  src/Agent.Worker/Handlers/NodeHandler.cs
Labels: bug

#3125 Update mingit to latest git version 2.28.0
  src/Misc/externals.sh
Labels: misc
