Repository microsoft/azure-pipelines-agent, pull requests merged in 2020-06, with the labels that each got.

#2994 Fix RHEL 6 agent link
  src/Misc/InstallAgentPackage.template.xml
Labels: internal

#2982 Don't extract 2 zips to the same directory
  src/Misc/externals.sh
Labels: internal

#2998 Reverse order of libcurl install
  src/Misc/layoutbin/installdependencies.sh
Labels: bug

#3003 Update dotnet-install.ps1
  src/Misc/dotnet-install.ps1
Labels: enhancement

#3008 Localize strings for Azure DevOps 2020 RC1.
  src/Misc/layoutbin/de-DE/strings.json
  src/Misc/layoutbin/es-ES/strings.json
  src/Misc/layoutbin/fr-FR/strings.json
  src/Misc/layoutbin/it-IT/strings.json
  src/Misc/layoutbin/ja-JP/strings.json
  src/Misc/layoutbin/ko-KR/strings.json
  src/Misc/layoutbin/ru-RU/strings.json
  src/Misc/layoutbin/zh-CN/strings.json
  src/Misc/layoutbin/zh-TW/strings.json
Labels: internal

#3002 Agent no-logs mode
  src/Agent.Listener/CommandLine/ConfigureAgent.cs
  src/Agent.Listener/CommandSettings.cs
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Microsoft.VisualStudio.Services.Agent/ConfigurationStore.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: Area: Build, enhancement

#3009 Various release PR fixes
  .vsts.release.yml
  release/createAdoPr.js
Labels: internal

#3017 Changed thread.sleep to task.delay
  src/Agent.Plugins/TfsVCCliManager.cs
Labels: internal

#2979 Upload even with 0 result
  src/Agent.Worker/TestResults/Legacy/LegacyTestRunDataPublisher.cs
Labels: enhancement

#3018 Support AutoLogon + RunOnce
  src/Agent.Listener/CommandLine/ConfigureAgent.cs
  src/Agent.Listener/CommandSettings.cs
  src/Agent.Listener/Configuration.Windows/AutoLogonRegistryManager.cs
  src/Test/L0/Listener/Configuration/AgentAutoLogonTestL0.cs
Labels: enhancement

#3024 Add Agent.OSVersion support of Mac OS X agents.
  src/Microsoft.VisualStudio.Services.Agent/Capabilities/AgentCapabilitiesProvider.cs
Labels: enhancement

#3019 Retry TFVC Workspaces
  src/Agent.Plugins/TFCliManager.cs
  src/Agent.Plugins/TeeCliManager.cs
  src/Agent.Plugins/TfsVCCliManager.cs
Labels: enhancement

#3006 Update of NodeJS to solved Vulnerabilities (#3007)
  src/Misc/externals.sh
Labels: enhancement

#3025 Dont trim line break characters from inputs
  src/Agent.Worker/TaskRunner.cs
  src/Test/L1/Worker/WorkerL1Tests.cs
Labels: bug
