Repository microsoft/azure-pipelines-agent, pull requests merged in 2020-07, with the labels that each got.

#3037 Fix Powershell test
  src/Misc/dotnet-install.ps1
Labels: internal

#3036 Propagate system.debug to Pipeline Artifact logging
  src/Agent.Plugins/ArtifactsTracer.cs
  src/Agent.Plugins/PipelineArtifact/DedupManifestArtifactClientFactory.cs
  src/Agent.Plugins/PipelineArtifact/FilePathServer.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPlugin.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV1.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV2.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
  src/Agent.Plugins/PipelineCache/TarUtils.cs
  src/Agent.Sdk/TaskPlugin.cs
  src/Test/L0/Plugin/TestFileShareProvider/TestFileShareProviderL0.cs
Labels: enhancement

#2904 Minimal support for SELinux in svc.sh
  src/Misc/layoutbin/systemd.svc.sh.template
Labels: enhancement

#3035 Add variable with mapping between container alias and name
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
Labels: internal

#3030 Grammer and casing.
  src/Agent.Worker/Release/ReleaseTrackingManager.cs
  src/Misc/layoutbin/de-DE/strings.json
  src/Misc/layoutbin/en-US/strings.json
  src/Misc/layoutbin/es-ES/strings.json
  src/Misc/layoutbin/fr-FR/strings.json
  src/Misc/layoutbin/it-IT/strings.json
  src/Misc/layoutbin/ja-JP/strings.json
  src/Misc/layoutbin/ko-KR/strings.json
  src/Misc/layoutbin/ru-RU/strings.json
  src/Misc/layoutbin/zh-CN/strings.json
  src/Misc/layoutbin/zh-TW/strings.json
Labels: bug

#3039 Upgrade Windows Process Priority
  src/Agent.Listener/Program.cs
Labels: Area: Core, enhancement

#3046 Revert "Dont trim line break characters from inputs (#3025)"
  src/Agent.Worker/TaskRunner.cs
  src/Test/L1/Worker/WorkerL1Tests.cs
Labels: bug

#3048 Revert "made RunPorcelainCommandAsync and RunPorcelainCommandAsync wi…
  src/Agent.Plugins/TFCliManager.cs
  src/Agent.Plugins/TeeCliManager.cs
  src/Agent.Plugins/TfsVCCliManager.cs
Labels: bug

#3051 Add option to not trim inputs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/TaskRunner.cs
  src/Test/L1/Worker/WorkerL1Tests.cs
Labels: bug

#3032 Retry over workfoldmap
  src/Agent.Plugins/TFCliManager.cs
  src/Agent.Plugins/TfsVCCliManager.cs
Labels: enhancement

#3050 Fix RunCommandAsync retry logic
  src/Agent.Plugins/TfsVCCliManager.cs
Labels: bug

#3052 Correct Move behavior for Multi-Repo Checkout
  src/Agent.Worker/Build/BuildDirectoryManager.cs
Labels: Area: Core, bug

#3060 Allow Checkout to continue if "git lfs fetch" fails
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Plugins/GitSourceProvider.cs
Labels: Area: Core, bug

#3055 added retry to tf workspaces
  src/Agent.Plugins/TFCliManager.cs
  src/Agent.Plugins/TeeCliManager.cs
  src/Agent.Plugins/TfsVCCliManager.cs
Labels: bug

#2822 Break L1s into multiple classes
  src/Test/L1/Mock/FakeAgentPluginManager.cs
  src/Test/L1/Mock/FakeBuildServer.cs
  src/Test/L1/Mock/FakeConfigurationStore.cs
  src/Test/L1/Mock/FakeCustomerIntelligenceServer.cs
  src/Test/L1/Mock/FakeJobServer.cs
  src/Test/L1/Mock/FakeReleaseServer.cs
  src/Test/L1/Mock/FakeTaskManager.cs
  src/Test/L1/Mock/FakeTaskServer.cs
  src/Test/L1/Plugins/FakeCheckoutTask.cs
  src/Test/L1/Plugins/FakeGitCliManager.cs
  src/Test/L1/Worker/CheckoutL1Tests.cs
  src/Test/L1/Worker/ConditionsL1Tests.cs
  src/Test/L1/Worker/ConfigL1Tests.cs
  src/Test/L1/Worker/ContainerL1Tests.cs
  src/Test/L1/Worker/CoreL1Tests.cs
  src/Test/L1/Worker/L1TestBase.cs
  src/Test/L1/Worker/SigningL1Tests.cs
  src/Test/L1/Worker/VariableL1Tests.cs
  src/Test/L1/Worker/WorkerL1Tests.cs
Labels: internal
