Repository microsoft/azure-pipelines-agent, pull requests merged in 2020-10, with the labels that each got.

#3127 Turn on Fetch By Commit For GitHub
  src/Agent.Plugins/GitSourceProvider.cs
Labels: Area: Core, enhancement

#3139 Remove all warnings from build output
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Plugins/PipelineArtifact/IArtifactProvider.cs
  src/Agent.Plugins/PipelineArtifact/Telemetry/FileShareActionRecord.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
  src/Agent.Sdk/CommandPlugin.cs
  src/Agent.Sdk/ExecutionTargetInfo.cs
  src/Agent.Sdk/LogPlugin.cs
  src/Agent.Sdk/Util/IOUtil.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Sdk/Util/StringUtil.cs
  src/Agent.Worker/AsyncCommandContext.cs
  src/Agent.Worker/Build/GitSourceProvider.cs
  src/Agent.Worker/Build/TrackingConfigHashAlgorithm.cs
  src/Agent.Worker/CodeCoverage/CodeCoverageServer.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/ExpressionManager.cs
  src/Microsoft.VisualStudio.Services.Agent/JobServerQueue.cs
  src/Microsoft.VisualStudio.Services.Agent/Logging.cs
  src/Microsoft.VisualStudio.Services.Agent/ProcessChannel.cs
  src/rules.ruleset
Labels: internal

#2834 Multiple directories and path glob pattern support for pipeline caching
  src/Agent.Plugins/PipelineCache/FingerprintCreator.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheTaskPluginBase.cs
  src/Agent.Plugins/PipelineCache/RestorePipelineCacheV0.cs
  src/Agent.Plugins/PipelineCache/SavePipelineCacheV0.cs
  src/Agent.Plugins/PipelineCache/TarUtils.cs
  src/Test/L0/Plugin/FingerprintCreatorTests.cs
  src/Test/L0/Plugin/IsPathyTests.cs
  src/Test/L0/Plugin/TarUtilsL0.cs
Labels: enhancement

#3142 Add retries on PA downloads
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactProvider.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactServer.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
  src/Agent.Plugins/PipelineCache/RestorePipelineCacheV0.cs
  src/Agent.Plugins/PipelineCache/SavePipelineCacheV0.cs
Labels: Area: Core, enhancement

#3147 Update dotnet installer
  src/Misc/dotnet-install.ps1
  src/Misc/dotnet-install.sh
Labels: internal

#3150 L1 test for Node 10
  src/Misc/externals.sh
  src/Test/L1/Worker/CoreL1Tests.cs
  src/Test/L1/Worker/L1TestBase.cs
Labels: internal
