Repository microsoft/azure-pipelines-agent, pull requests merged in 2020-11, with the labels that each got.

#3152 Escape percents
  docs/design/percentEncoding.md
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/TaskPlugin.cs
  src/Agent.Worker/WorkerCommandManager.cs
  src/Microsoft.VisualStudio.Services.Agent/Command.cs
  src/Test/L0/Worker/LoggingCommandL0.cs
Labels: enhancement

#3153 Bump the vss-api-netcore package version
  src/Common.props
Labels: enhancement

#3154 Upgrade tee to 14.135.0
  src/Misc/externals.sh
Labels: bug

#3151 Remove Node 14
  .azure-pipelines/signing.yml
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/HandlerFactory.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/TaskManager.cs
  src/Agent.Worker/TaskRunner.cs
  src/Misc/externals.sh
  src/Test/L0/NodeHandlerL0.cs
  src/Test/L0/Worker/TaskManagerL0.cs
Labels: internal

#3162 Update dotnet install script
  src/Misc/dotnet-install.ps1
  src/Misc/dotnet-install.sh
Labels: internal

#3163 Revert "Multiple directories and path glob pattern support for pipeline caching (#2834)"
  src/Agent.Plugins/PipelineCache/FingerprintCreator.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheTaskPluginBase.cs
  src/Agent.Plugins/PipelineCache/RestorePipelineCacheV0.cs
  src/Agent.Plugins/PipelineCache/SavePipelineCacheV0.cs
  src/Agent.Plugins/PipelineCache/TarUtils.cs
  src/Test/L0/Plugin/FingerprintCreatorTests.cs
  src/Test/L0/Plugin/IsPathyTests.cs
  src/Test/L0/Plugin/TarUtilsL0.cs
Labels: bug

#3165 Establish the first Vss connection before doing the rest in parallel
  src/Microsoft.VisualStudio.Services.Agent/AgentServer.cs
Labels: enhancement

#3166 Removed AAD authentication support from MacOS
  src/Agent.Listener/Configuration/CredentialProvider.cs
Labels: Area: Core, bug

#3141 Node.js 10.x Vulnerabilities update to v10.22.1
  src/Misc/externals.sh
Labels: enhancement
