Repository microsoft/azure-pipelines-agent, pull requests merged in 2020-12, with the labels that each got.

#3179 Fixed installdependencies.sh script for Ubuntu 20.04
  src/Misc/layoutbin/installdependencies.sh
Labels: bug

#3174 Bumped nuget version
  src/Misc/externals.sh
Labels: bug

#3177 Extract tasks on every step for AlwaysExtractTask
  src/Agent.Worker/TaskRunner.cs
  src/Test/L0/Worker/TaskRunnerL0.cs
Labels: Area: Core, bug

#3182 [Security] Add a check of the agent's root directory access rules
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement

#3183 Update Agent.OSVersion support of Mac OS X Big Sur agents.
  src/Microsoft.VisualStudio.Services.Agent/Capabilities/AgentCapabilitiesProvider.cs
Labels: bug

#3186 Update Agent.OSVersion support fot .net 5 and later
  src/Microsoft.VisualStudio.Services.Agent/Capabilities/AgentCapabilitiesProvider.cs
Labels: enhancement

#3170 Add pipelines-agent-* packages without Node 6
  .azure-pipelines/build-job.yml
  .azure-pipelines/build-jobs.yml
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
  .vsts.release.yml
  assets.json
  docs/node6.md
  releaseNote.md
  src/Agent.Listener/SelfUpdater.cs
  src/Misc/InstallAgentPackage.template.xml
  src/Misc/externals.sh
  src/dev.sh
  src/dir.proj
Labels: enhancement
