Repository microsoft/azure-pipelines-agent, pull requests merged in 2020-04, with the labels that each got.

#2883 Move proxy vars to knobs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Knob/RuntimeKnobSource.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Microsoft.VisualStudio.Services.Agent/VstsAgentWebProxy.cs
  src/Test/L0/TestHostContext.cs
Labels: enhancement

#2888 Enable one linting rule, changes for another
  src/Agent.Listener/Configuration.Windows/AutoLogonManager.cs
  src/Agent.Listener/Configuration.Windows/AutoLogonRegistryManager.cs
  src/Agent.Listener/Configuration.Windows/NativeWindowsServiceHelper.cs
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/Configuration/PromptManager.cs
  src/Agent.Listener/DistributedTask.Pipelines/Yaml/PipelineParser.cs
  src/Agent.Worker/Build/FileContainerServer.cs
  src/Agent.Worker/Handlers/LegacyPowerShellHandler.cs
  src/Agent.Worker/Handlers/PowerShellExeHandler.cs
  src/Agent.Worker/PluginInternalCommandExtension.cs
  src/Agent.Worker/Release/Artifacts/GenericHttpClient.cs
  src/Agent.Worker/Release/ContainerFetchEngine/FetchEngine.cs
  src/Agent.Worker/Release/ReleaseCommandExtension.cs
  src/Agent.Worker/TaskCommandExtension.cs
  src/Agent.Worker/TaskRunner.cs
  src/Microsoft.VisualStudio.Services.Agent/Util/PowerShellExeUtil.cs
  src/Test/L0/Listener/Configuration/PromptManagerTestsL0.cs
  src/Test/L0/ProcessExtensionL0.cs
  src/Test/L0/Worker/PluginInternalUpdateRepositoryPathCommandL0.cs
  src/Test/L0/Worker/TaskCommandExtensionL0.cs
  src/rules.ruleset
Labels: internal

#2891 Command Line Parser Fixes
  src/Agent.Listener/CommandLine/ConfigureAgent.cs
  src/Agent.Listener/CommandLine/RunAgent.cs
  src/Agent.Listener/CommandSettings.cs
  src/Test/L0/Listener/CommandSettingsL0.cs
Labels: bug

#2890 Remove mkrelease and move createReleaseBranch to octokit
  release/createAdoPrs.js
  release/createReleaseBranch.js
  release/mkrelease.js
  release/package-lock.json
  release/package.json
Labels: internal

#2895 Fix undefined vars in createReleaseBranch.js
  release/createReleaseBranch.js
Labels: internal

#2896 Hide uri rules
  src/rules.ruleset
Labels: internal

#2889 Move some util configurations to knobs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Knob/KnobValue.cs
  src/Agent.Sdk/Util/IOUtil.cs
  src/Agent.Sdk/Util/UtilKnobValueContext.cs
  src/Agent.Sdk/Util/VssUtil.cs
  src/Agent.Worker/Release/Artifacts/GitHubHttpClient.cs
Labels: enhancement

#2897 Disable ARM64 jobs
  .vsts.ci.yml
  .vsts.release.yml
Labels: internal

#2898 Convert some more vars to knobs and remove legacy code
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/IOUtil.cs
  src/Agent.Sdk/Util/UtilKnobValueContext.cs
  src/Agent.Sdk/Util/VssUtil.cs
  src/Agent.Worker/Handlers/Handler.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Microsoft.VisualStudio.Services.Agent/TraceSetting.cs
Labels: enhancement

#2900 Only run codeanalysis on build
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.PluginHost/Agent.PluginHost.csproj
  src/Agent.Plugins/Agent.Plugins.csproj
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Sdk/Knob/RuntimeKnobSource.cs
  src/Agent.Service/Windows/AgentService.csproj
  src/Agent.Worker/Agent.Worker.csproj
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
  src/Test/L0/ProcessExtensionL0.cs
  src/dev.sh
Labels: internal

#2879 #2801 update NODE10_VERSION to version 10.19.0 to resolved vulnerability
  src/Misc/externals.sh
Labels: bug

#2906 Update dotnet install script
  src/Misc/dotnet-install.sh
Labels: internal

#2905 Hide culture rules
  src/rules.ruleset
Labels: internal

#2909 Fix overzealous argument null checking
  src/Microsoft.VisualStudio.Services.Agent/JobNotification.cs
Labels: bug

#2908 Mover prefergitfrompath to knob
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/GitSourceProvider.cs
  src/Test/L0/Worker/Build/GitSourceProviderL0.cs
Labels: enhancement

#2913 More configurations to knobs and make preferPowerShellOnContainers true by default
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/TaskCommandExtension.cs
  src/Agent.Worker/TaskRunner.cs
  src/Agent.Worker/TempDirectoryManager.cs
  src/Test/L0/Worker/TaskRunnerL0.cs
Labels: enhancement

#2915 Re-work pipelines YAML using extends and parameters
  .azure-pipelines/build-job.yml
  .azure-pipelines/package-vcredist.yml
  .azure-pipelines/pipeline.yml
  .azure-pipelines/signing.yml
  .azure-pipelines/switch-branch.yml
  .vsts.ci.yml
  .vsts.release.yml
  .vsts.template.nonwindows.yml
  .vsts.template.windows.yml
Labels: internal

#2907 More knobs
  src/Agent.Listener/SelfUpdater.cs
  src/Agent.Sdk/CommandPlugin.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/TaskPlugin.cs
  src/Agent.Worker/TaskManager.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
Labels: enhancement

#2917 A few more knobs
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Agent.Worker/JobRunner.cs
Labels: enhancement

#2919 Add parameter for build target selection
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
Labels: enhancement

#2920 Sign Mac DLLs
  .azure-pipelines/build-job.yml
  .azure-pipelines/pipeline.yml
  .azure-pipelines/signing.yml
Labels: internal

#2922 Sign Linux x64 DLLs
  .azure-pipelines/pipeline.yml
Labels: internal

#2918 Organize agent knobs
  src/Agent.Sdk/Knob/AgentKnobs.cs
Labels: internal

#2925 Remove recently added Dispose
  src/Agent.Worker/Release/Artifacts/BuildArtifact.cs
  src/Agent.Worker/Release/ContainerProvider/Helpers/ContainerProviderFactory.cs
Labels: bug

#2933 Update MinGit to 2.26.2
  src/Misc/externals.sh
Labels: misc

#2934 Add setup_info support from Actions Runner
  src/Agent.Worker/JobExtension.cs
  src/Microsoft.VisualStudio.Services.Agent/ConfigurationStore.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Test/L0/TestHostContext.cs
  src/Test/L0/Worker/JobExtensionL0.cs
  src/Test/L1/Mock/FakeConfigurationStore.cs
Labels: enhancement

#2940 document --gitUseSChannel
  src/Misc/layoutbin/en-US/strings.json
Labels: internal

#2943 Adding the ability to run a single L0/L1 test
  src/Misc/externals.sh
  src/dev.sh
  src/dir.proj
Labels: enhancement

#2926 Flaky Implementation for PTR in linux agent
  src/Agent.Worker/TestResults/Legacy/LegacyTestRunDataPublisher.cs
  src/Agent.Worker/TestResults/Legacy/TestResultsServer.cs
  src/Agent.Worker/TestResults/Legacy/TestRunPublisher.cs
  src/Agent.Worker/TestResults/TestDataPublisher.cs
  src/Agent.Worker/TestResults/TestRunDataPublisherHelper.cs
  src/Agent.Worker/TestResults/Utils/InputValidator.cs
  src/Agent.Worker/TestResults/Utils/PublisherInputValidator.cs
  src/Agent.Worker/TestResults/Utils/RetryHelper.cs
  src/Agent.Worker/TestResults/Utils/SimpleTimer.cs
  src/Agent.Worker/TestResults/Utils/TestResultsConstants.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
Labels: enhancement

#2945 Adding L1 tests for TestConfig scenarios
  src/Test/L1/Worker/L1TestBase.cs
  src/Test/L1/Worker/WorkerL1Tests.cs
Labels: enhancement

#2949 branch in createReleaseBranch.js was undefined
  release/createReleaseBranch.js
Labels: bug

#2950 Separate targets flags and add skipTests
  .azure-pipelines/build-job.yml
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
  .vsts.release.yml
Labels: internal

#2936 Adding troubleshooting section to contribute.md
  docs/contribute.md
Labels: documentation

#2768 Adding Repos hash to the config folder structure under SourceRootMapping
  src/Agent.Sdk/TaskPlugin.cs
  src/Agent.Worker/Build/TrackingConfig.cs
  src/Agent.Worker/Build/TrackingManager.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Test/L1/Worker/L1TestBase.cs
  src/Test/L1/Worker/WorkerL1Tests.cs
Labels: enhancement
