Repository microsoft/azure-pipelines-agent, pull requests merged in 2021-05, with the labels that each got.

#3372 Removed 'Always extract tasks option' as prompt - leaved only as argument
  src/Agent.Listener/CommandSettings.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement

#3389 Fix PostLines speed changes
  src/Microsoft.VisualStudio.Services.Agent/JobServerQueue.cs
Labels: bug

#3393 Resolve Security Analysis warnings
  src/Agent.Listener/NuGet.Config
  src/Agent.Worker/NuGet.Config
  src/Microsoft.VisualStudio.Services.Agent/NuGet.Config
  src/NuGet.Config
  src/Test/NuGet.Config
  tools/CredScanRegexes/nuget.config
Labels: internal

#3392 Specified working directory explicitly for 'docker exec' command - to align behavior with last docker fix
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Agent.Worker/Handlers/StepHost.cs
Labels: bug

#3405 Remove unneeded blob telemetry
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobStoreClientTelemetryTfs.cs
Labels: bug

#3381 Added capability detection for JDK/JRE >=9 as 'java'/'JDK' capabilities
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Misc/layoutbin/powershell/Add-JavaCapabilities.ps1
  src/Misc/layoutbin/powershell/CapabilityHelpers/CapabilityFunctions.ps1
  src/Misc/layoutbin/powershell/CapabilityHelpers/CapabilityHelpers.psm1
  src/Misc/layoutbin/powershell/CapabilityHelpers/RegistryFunctions.ps1
  src/Misc/layoutbin/powershell/CapabilityHelpers/VersionFunctions.ps1
Labels: bug

#3410 Adjusted code sign step - to sign new assemblies
  .azure-pipelines/signing.yml
Labels: bug

#3408 Updating vss-api-nuget package - catching Exception for blobstore client telemetry
  src/Common.props
Labels: Area: Core, enhancement

#3411 Update dotnet install scripts 5/20/2021
  src/Misc/dotnet-install.ps1
  src/Misc/dotnet-install.sh
Labels: internal

#3336 Auth agent docs - added more details for rsa private key file
  docs/design/auth.md
Labels: documentation, misc

#3397 Bundle git-lfs.exe with the agent
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Worker/Build/GitCommandManager.cs
  src/Misc/externals.sh
Labels: enhancement

#3419 Added auto assign action
  .github/workflows/autoAssignABTT.yml
Labels: enhancement

#3420 Backward-compat support setting proxy via environment variables
  src/Agent.Sdk/TaskPlugin.cs
Labels: enhancement

#3426 Add temporary env variable to disable blob integration
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/FileContainerServer.cs
Labels: enhancement

#3425 Optimize DownloadBuildArtifactsV1
  src/Agent.Plugins/Artifact/ArtifactProviderFactory.cs
  src/Agent.Plugins/Artifact/FileContainerProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactConstants.cs
  src/Agent.Plugins/BuildArtifact/BuildArtifactDownloadRecord.cs
Labels: enhancement

#3427 Auto assign action - fixed token, area label name
  .github/workflows/autoAssignABTT.yml
Labels: misc
