Repository microsoft/azure-pipelines-agent, pull requests merged in 2021-01, with the labels that each got.

#3205 Temporarily remove aspnetcidev and associated test
  src/Test/L0/Plugin/ChunkerTests.cs
  src/Test/NuGet.Config
Labels: internal

#3187 Update logging to use the blobstore service
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/JobServer.cs
  src/Microsoft.VisualStudio.Services.Agent/JobServerQueue.cs
  src/Test/L0/PagingLoggerL0.cs
  src/Test/L1/Mock/FakeJobServer.cs
  src/Test/L1/Worker/ContainerL1Tests.cs
  src/Test/L1/Worker/CoreL1Tests.cs
  src/Test/L1/Worker/L1TestBase.cs
  src/Test/L1/Worker/SigningL1Tests.cs
  src/Test/L1/Worker/VariableL1Tests.cs
Labels: enhancement

#3208 Try the new prod deployment pool
  .vsts.release.yml
Labels: internal

#3222 Update dotnet install script
  src/Misc/dotnet-install.ps1
  src/Misc/dotnet-install.sh
Labels: internal

#3173 Added ability to mount 'tasks' volume readonly on Windows
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/ContainerOperationProvider.cs
Labels: enhancement

#3216 Added libicu67 to installdependencies.sh
  src/Misc/layoutbin/installdependencies.sh
Labels: enhancement

#3204 Fix percent encoding knobs
  docs/design/percentEncoding.md
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/TaskPlugin.cs
  src/Agent.Worker/WorkerCommandManager.cs
  src/Microsoft.VisualStudio.Services.Agent/Capabilities/PowerShellCapabilitiesProvider.cs
  src/Microsoft.VisualStudio.Services.Agent/Command.cs
  src/Test/L0/Worker/LoggingCommandL0.cs
Labels: bug

#3223 Protect Network Call during Client Creation with Retries
  src/Agent.Plugins/PipelineArtifact/DedupManifestArtifactClientFactory.cs
  src/Agent.Plugins/PipelineArtifact/FileShareProvider.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactProvider.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactServer.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
Labels: bug

#3226 Fix status banners
  README.md
Labels: internal

#3229 Update node-fetch dependency
  release/package-lock.json
Labels: internal

#3227 Improving the MaxSubResultLimitReached message
  src/Misc/layoutbin/en-US/strings.json
Labels: bug
