Repository microsoft/azure-pipelines-agent, pull requests merged in 2021-11, with the labels that each got.

#3573 Fix for issue 3520 - disabling of inputs translating for checkout tasks
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/StepsRunner.cs
  src/Agent.Worker/TaskRunner.cs
  src/Agent.Worker/Variables.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
Labels: bug

#3581 Bump recommended Git version, fix prune-tags for older versions
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Worker/Build/GitCommandManager.cs
Labels: enhancement

#3592 Add warning message for Node 6 handler
  src/Agent.Worker/Handlers/HandlerFactory.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement

#3589 Try to delete the workspace instead of fail
  src/Agent.Plugins/TfsVCSourceProvider.cs
Labels: bug

#3594 Added test TranslatePathForStepTarget_should_convert_path_only_for_containers
  src/Test/L0/Worker/ExecutionContextL0.cs
Labels: Area: Test, misc, Area: ABTT, Area: Agent

#3586 Fixed result for MergeTrackingConfigs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/BuildDirectoryManager.cs
  src/Agent.Worker/Build/TrackingManager.cs
Labels: bug

#3591 Better warnings for BlobStore errors
  src/Agent.Plugins/Artifact/FileContainerProvider.cs
  src/Agent.Sdk/Util/BlobStoreWarningInfoProvider.cs
  src/Agent.Worker/Build/FileContainerServer.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement

#3607 Node 6 removal warning - added end of support date
  src/Agent.Worker/Handlers/HandlerFactory.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: misc

#3608 Update VssApiVersion to 0.5.172-private
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobStoreClientTelemetryTfs.cs
Labels: enhancement, Area: Core

#3601 RHEL/CentOS 7 Fix for Let’s Encrypt Change
  src/Misc/layoutbin/installdependencies.sh
Labels: misc

#3613 Add condition to yum installation of lttng-ust
  src/Misc/layoutbin/installdependencies.sh
Labels: enhancement

#3568 Improve error messaging for SSL related errors
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/Configuration/ConfigurationProvider.cs
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.Listener/SelfUpdater.cs
  src/Agent.Sdk/CommandPlugin.cs
  src/Agent.Sdk/LogPlugin.cs
  src/Agent.Sdk/TaskPlugin.cs
  src/Agent.Sdk/Util/SslUtil.cs
  src/Agent.Sdk/Util/VssUtil.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/Release/Artifacts/BuildArtifact.cs
  src/Agent.Worker/Release/ContainerProvider/FileContainerProvider.cs
  src/Agent.Worker/Release/ContainerProvider/Helpers/VssConnectionFactory.cs
  src/Agent.Worker/WorkerUtilties.cs
  src/Microsoft.VisualStudio.Services.Agent/AgentServer.cs
  src/Microsoft.VisualStudio.Services.Agent/Util/ServerUtil.cs
  src/Test/L0/Util/VssUtilL0.cs
Labels: enhancement

#3621 Rolling back retry handling on GetPipelineCacheArtifactAsync
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
Labels: bug

#3623 Added knob to disable Node 6 deprecation warnings
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/HandlerFactory.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement

#3633 Turn off Node 6 execution handler deprecation warning for in-the-box tasks
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/HandlerFactory.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Misc/layoutbin/tasks-exception-list.json
Labels: bug

#3635 Patch for Agent v2.195.0 - Node6 execution handler warnings
  releaseNote.md
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/HandlerFactory.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Misc/layoutbin/en-US/strings.json
  src/Misc/layoutbin/tasks-exception-list.json
  src/agentversion
Labels: bug

#3637 Add OneLocBuild removal to the localization pipeline
  Localize/localize-pipeline.yml
Labels: enhancement

#3614 Warnings instead of exceptions for ConfigurationManager if deployment type has not been determined
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/SelfUpdater.cs
  src/Microsoft.VisualStudio.Services.Agent/Util/ServerUtil.cs
Labels: bug
