Repository microsoft/azure-pipelines-agent, pull requests merged in 2021-02, with the labels that each got.

#3231 Should ignore PSModulePath
  src/Microsoft.VisualStudio.Services.Agent/Capabilities/EnvironmentCapabilitiesProvider.cs
Labels: enhancement

#3234 Fix typo
  docs/design/percentEncoding.md
Labels: internal

#3230 Skip task's post-execution step if target container stopped
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Container/DockerCommandManager.cs
  src/Agent.Worker/TaskRunner.cs
Labels: enhancement

#3240 Update dotnet install script
  src/Misc/dotnet-install.ps1
  src/Misc/dotnet-install.sh
Labels: internal

#3246 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20210207214653129 to Localization
  Localize/loc/de-de/src/Agent.Service/Windows/Resource.resx.lcl
  Localize/loc/es-es/src/Agent.Service/Windows/Resource.resx.lcl
  Localize/loc/fr-fr/src/Agent.Service/Windows/Resource.resx.lcl
  Localize/loc/it-IT/src/Agent.Service/Windows/Resource.resx.lcl
  Localize/loc/ja-jp/src/Agent.Service/Windows/Resource.resx.lcl
  Localize/loc/ko-KR/src/Agent.Service/Windows/Resource.resx.lcl
  Localize/loc/ru-RU/src/Agent.Service/Windows/Resource.resx.lcl
  Localize/loc/zh-CN/src/Agent.Service/Windows/Resource.resx.lcl
  Localize/loc/zh-TW/src/Agent.Service/Windows/Resource.resx.lcl
Labels: enhancement

#3241 Use %AZP25 instead of %25 for escaping
  docs/design/percentEncoding.md
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/TaskPlugin.cs
  src/Agent.Worker/Worker.cs
  src/Agent.Worker/WorkerCommandManager.cs
  src/Microsoft.VisualStudio.Services.Agent/Command.cs
  src/Test/L0/Worker/LoggingCommandL0.cs
Labels: enhancement

#3251 Force Npm 6
  .vsts.release.yml
Labels: internal

#3249 Add support for setvariable restrictions
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/JobExtension.cs
  src/Agent.Worker/TaskCommandExtension.cs
  src/Agent.Worker/TaskManager.cs
  src/Agent.Worker/WorkerCommandManager.cs
  src/Common.props
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L0/Worker/ExecutionContextL0.cs
  src/Test/L0/Worker/SetVariableRestrictionsL0.cs
  src/Test/L0/Worker/TaskManagerL0.cs
Labels: enhancement

#3253 Turn off % encoding warnings by default
  releaseNote.md
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Misc/dotnet-install.ps1
  src/Misc/dotnet-install.sh
  src/agentversion
Labels: bug

#3248 Added -y to yum updateinfo command
  src/Misc/layoutbin/installdependencies.sh
Labels: enhancement

#3237 Self-hosted agent cleaning source folder
  src/Agent.Worker/Build/BuildDirectoryManager.cs
  src/Agent.Worker/PluginInternalCommandExtension.cs
Labels: bug

#3260 #3259 Update NodeJS to version 10.23.3
  src/Misc/externals.sh
Labels: enhancement

#3262 Increased default value for AZP_AGENT_DOWNLOAD_TIMEOUT
  src/Agent.Sdk/Knob/AgentKnobs.cs
Labels: enhancement

#3254 Added ability to download artifacts from canceled builds.
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV2.cs
Labels: enhancement

#3267 Use node10 instead of node in runsvc.sh
  src/Misc/layoutbin/runsvc.sh
Labels: bug

#3268 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20210216210917466 to Localization
  Localize/loc/it-IT/src/Agent.Service/Windows/Resource.resx.lcl
  Localize/loc/ko-KR/src/Agent.Service/Windows/Resource.resx.lcl
  Localize/loc/zh-CN/src/Agent.Service/Windows/Resource.resx.lcl
Labels: enhancement

#3265 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20210212210623045 to Localization
  Localize/loc/fr-fr/src/Agent.Service/Windows/Resource.resx.lcl
Labels: enhancement

#3272 Update stale.yml
  .github/workflows/stale.yml
Labels: internal

#3232 Upload build artifacts to blobstore
  src/Agent.Plugins/PipelineArtifact/DedupManifestArtifactClientFactory.cs
  src/Agent.Plugins/PipelineArtifact/FileShareProvider.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactProvider.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactServer.cs
  src/Agent.Plugins/PipelineArtifact/Telemetry/PipelineArtifactActionRecord.cs
  src/Agent.Plugins/PipelineArtifact/Telemetry/PipelineTelemetryRecord.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
  src/Agent.Plugins/PipelineCache/TarUtils.cs
  src/Agent.Sdk/Blob/DedupManifestArtifactClientFactory.cs
  src/Agent.Sdk/Blob/PipelineTelemetryRecord.cs
  src/Agent.Worker/AsyncCommandContext.cs
  src/Agent.Worker/Build/BuildArtifactActionRecord.cs
  src/Agent.Worker/Build/FileContainerServer.cs
  src/Agent.Worker/RetryHelper.cs
  src/Agent.Worker/SimpleTimer.cs
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/JobServer.cs
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
Labels: enhancement

#3221 ResultsCommandExtension: Do not dispose the VssConnection
  src/Agent.Worker/TestResults/ResultsCommandExtension.cs
Labels: bug

#3256 Fix NullReferenceException when poolName is null
  src/Agent.Listener/Configuration/ServiceControlManager.cs
  src/Test/L0/Listener/Configuration/ServiceControlManagerL0.cs
Labels: bug

#3274 Fix clean parameter behavior in jobs with multiple checkouts
  src/Agent.Worker/Build/BuildJobExtension.cs
Labels: bug

#3287 Enable ARM64 CI
  .vsts.ci.yml
Labels: internal
