Repository microsoft/azure-pipelines-agent, pull requests merged in 2021-04, with the labels that each got.

#3349 Upgrade blob library to mask hash values
  src/Common.props
Labels: internal

#3355 Updated AttemptRemoveCredFromConfig message to display git config key
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Worker/Build/GitSourceProvider.cs
  src/Misc/layoutbin/de-DE/strings.json
  src/Misc/layoutbin/en-US/strings.json
  src/Misc/layoutbin/es-ES/strings.json
  src/Misc/layoutbin/fr-FR/strings.json
  src/Misc/layoutbin/it-IT/strings.json
  src/Misc/layoutbin/ja-JP/strings.json
  src/Misc/layoutbin/ko-KR/strings.json
  src/Misc/layoutbin/ru-RU/strings.json
  src/Misc/layoutbin/zh-CN/strings.json
  src/Misc/layoutbin/zh-TW/strings.json
Labels: Area: Agent, internal

#3288 add git lfs prune to maintenance job #3283
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Worker/Build/GitCommandManager.cs
  src/Agent.Worker/Build/GitSourceProvider.cs
Labels: Area: Agent, enhancement

#3363 LEGO: check in for Localization to temporary branch.
  Localize/loc/ja-JP/src/Agent.Service/Windows/Resource.resx.lcl
Labels: misc

#3364 LEGO: check in for Localization to temporary branch.
  Localize/loc/de-DE/src/Agent.Service/Windows/Resource.resx.lcl
  Localize/loc/es-ES/src/Agent.Service/Windows/Resource.resx.lcl
  Localize/loc/ru-RU/src/Agent.Service/Windows/Resource.resx.lcl
Labels: misc

#3368 Revert MinGit to 2.30.2 again, due to LFS issues
  src/Misc/externals.sh
Labels: bug

#3370 Allow the server to control PostLines speed
  src/Agent.Listener/Agent.cs
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/Worker.cs
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/JobServerQueue.cs
  src/Microsoft.VisualStudio.Services.Agent/ProcessChannel.cs
  src/Test/L0/Listener/AgentL0.cs
Labels: enhancement

#3374 Create PR in OneLocBuild task only on third week of sprint
  Localize/localize-pipeline.yml
Labels: misc

#3377 Update NODE10_VERSION to 10.24.1 #3376
  src/Misc/externals.sh
Labels: enhancement

#3378 Added workflow for automerging PRs from LEGO system
  .github/workflows/localization-automerge.yml
Labels: misc

#3384 Sign Symstore.Interop.dll dependency
  .azure-pipelines/signing.yml
Labels: internal

#3375 Add telemetry for chunk-dedup build artifacts uploads
  src/Agent.Plugins/Artifact/FileContainerProvider.cs
  src/Agent.Plugins/Artifact/FileShareProvider.cs
  src/Agent.Plugins/PipelineArtifact/Telemetry/PipelineArtifactActionRecord.cs
  src/Agent.Worker/Build/BuildArtifactActionRecord.cs
  src/Agent.Worker/Build/FileContainerServer.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobStoreClientTelemetryTfs.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobStoreUtils.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/CustomerIntelligenceTelemetrySender.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/IDedupRecord.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/PipelineTelemetryRecord.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/TimelineRecordAttachmentTelemetryRecord.cs
  src/Microsoft.VisualStudio.Services.Agent/JobServer.cs
  src/Microsoft.VisualStudio.Services.Agent/JobServerQueue.cs
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
  src/Test/L0/ServiceInterfacesL0.cs
  src/Test/L1/Mock/FakeJobServer.cs
Labels: internal
