Repository microsoft/azure-pipelines-agent, pull requests merged in 2021-12, with the labels that each got.

#3616 Issue 1836 - Adding of handling for exceptions "An existing connection was forcibly closed by the remote host"
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/Configuration/ConfigurationProvider.cs
  src/Agent.Listener/Configuration/CredentialProvider.cs
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.Listener/MessageListener.cs
  src/Agent.Listener/SelfUpdater.cs
  src/Agent.PluginHost/Program.cs
  src/Agent.Plugins/Artifact/FileContainerProvider.cs
  src/Agent.Plugins/TestFilePublisher/Plugin/TestFilePublisherLogPlugin.cs
  src/Agent.Plugins/TestResultParser/Plugin/TestResultLogPlugin.cs
  src/Agent.Plugins/TestResultParser/Telemetry/TelemetryConstants.cs
  src/Agent.Sdk/Util/ExceptionsUtil.cs
  src/Agent.Worker/Build/FileContainerServer.cs
  src/Agent.Worker/CodeCoverage/CodeCoverageCommands.cs
  src/Agent.Worker/Release/Artifacts/GitHubArtifact.cs
  src/Agent.Worker/Release/Artifacts/JenkinsArtifact.cs
  src/Agent.Worker/Release/ContainerProvider/FileContainerProvider.cs
  src/Agent.Worker/Release/ReleaseJobExtension.cs
  src/Agent.Worker/Release/ReleaseServer.cs
  src/Agent.Worker/Telemetry/TelemetryCommandExtension.cs
  src/Agent.Worker/WorkerCommandManager.cs
  src/Microsoft.VisualStudio.Services.Agent/AgentServer.cs
  src/Microsoft.VisualStudio.Services.Agent/JobServer.cs
  src/Microsoft.VisualStudio.Services.Agent/LocationServer.cs
Labels: enhancement, Area: ABTT, Area: Agent

#3609 Issue 1769 - part 1 - Adding of handling for AggregateExceptions
  src/Agent.Listener/Agent.cs
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.PluginHost/Program.cs
  src/Agent.Sdk/Util/ExceptionsUtil.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/Program.cs
Labels: enhancement, Area: ABTT, Area: Agent

#3618 Fix bug with AZURE_PIPELINES_DEDUP_PARALLELISM not being enforced
  src/Agent.Plugins/Artifact/FileContainerProvider.cs
  src/Agent.Plugins/Artifact/FileShareProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactServer.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
  src/Agent.Worker/Build/FileContainerServer.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
  src/Microsoft.VisualStudio.Services.Agent/ConfigurationStore.cs
  src/Microsoft.VisualStudio.Services.Agent/JobServer.cs
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
Labels: bug

#3648 Suppressed Node 6 deprecation warnings
  src/Agent.Sdk/Knob/AgentKnobs.cs
Labels: bug

#3650 Patch for Agent v2.195.1 - Suppression of Node 6 deprecation warnings
  releaseNote.md
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/agentversion
Labels: bug

#3636 Corrected agent's process on updating in a container
  src/Misc/layoutroot/run-docker.sh
Labels: bug

#3642 Sync send timeout of dedup client to VssConnection timeout settings
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
Labels: bug

#3611 Remove signing for third party libraries in agent release flow
  .azure-pipelines/scripts/Get-SigntoolPath.ps1
  .azure-pipelines/scripts/RemoveSignatureForThirdPartyAssemlies.ps1
  .azure-pipelines/scripts/RemoveSignatureScript.ps1
  .azure-pipelines/signing.yml
Labels: misc

#3652 Fix masking for url with auth data
  src/Microsoft.VisualStudio.Services.Agent/AdditionalMaskingRegexes.CredScan.cs
  src/Microsoft.VisualStudio.Services.Agent/AdditionalMaskingRegexes.cs
  src/Test/L0/SecretMaskerTests/SecretMaskerL0.cs
Labels: bug

#3654 Issue 3638 - Fixed the change source directory and workspace if a similar tracking config is existing
  src/Agent.Worker/Build/TrackingManager.cs
Labels: bug

#3535 Added authenticode validation for agent
  src/Agent.Listener/SelfUpdater.cs
  src/Agent.Listener/ValidationHelper/InstallerVerifier.cs
  src/Agent.Listener/ValidationHelper/UnsafeNativeMethods.cs
  src/Agent.Listener/ValidationHelper/Utility.cs
  src/Agent.Listener/ValidationHelper/VerificationException.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
Labels: enhancement

#3657 Add additional clean up command to delete all extraheader headers or warm
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Plugins/GitSourceProvider.cs
Labels: bug

#3663 Migrate win x86 release pipleine to Azure DevOps pool
  .azure-pipelines/build-job.yml
  .azure-pipelines/pipeline.yml
  src/Microsoft.VisualStudio.Services.Agent/WindowsEnvVarHelper.cs
  src/Test/Test.csproj
  src/dev.sh
  src/dir.proj
Labels: misc

#3675 Added L0 tests for TrackingManager - MergeTrackingConfigs method
  src/Agent.Worker/Build/BuildDirectoryManager.cs
  src/Agent.Worker/Build/TrackingManager.cs
  src/Test/L0/Worker/Build/TrackingManagerL0.cs
Labels: enhancement

#3661 Disabled masking for non-secret fields of service connection
  src/Agent.Sdk/Util/MaskingUtil.cs
  src/Agent.Worker/Worker.cs
Labels: bug

#3676 Patch for Agent v2.196.1 - Removing of changing source directory if It already exists and adding of tests for this
  releaseNote.md
  src/Agent.Worker/Build/BuildDirectoryManager.cs
  src/Agent.Worker/Build/TrackingManager.cs
  src/Test/L0/Worker/Build/TrackingManagerL0.cs
  src/agentversion
Labels: bug

#3664 Porting logic of handling negative patterns for DownloadBuildArtifacts task
  src/Agent.Plugins/Artifact/ArtifactItemFilters.cs
  src/Agent.Plugins/Artifact/FileContainerProvider.cs
Labels: bug

#3665 Added tests for ported logic of handling negative patterns for DownloadBuildArtifacts task
  src/Agent.Plugins/Artifact/ArtifactItemFilters.cs
  src/Test/L0/Plugin/TestFileContainerProvider/TestFileContainerProviderL0.cs
Labels: bug

#3666 Adding support of negative patterns for DownloadBuildArtifacts task in scenarios with using file share
  src/Agent.Plugins/Artifact/ArtifactItemFilters.cs
  src/Agent.Plugins/Artifact/FileShareProvider.cs
Labels: bug

#3677 Added RepoType telemetry for checkout task
  src/Agent.Plugins/RepositoryPlugin.cs
Labels: enhancement

#3679 Enabling validation of checksum for online agent update for ADO OnPrem
  src/Agent.Listener/SelfUpdater.cs
Labels: enhancement

#3681 Add passive validation - dumping cloud-init logs
  src/Agent.Worker/DiagnosticLogManager.cs
Labels: enhancement
