Repository microsoft/azure-pipelines-agent, pull requests merged in 2021-09, with the labels that each got.

#3517 Add agent package hashes to metadata and release notes
  .azure-pipelines/build-job.yml
  .gitignore
  .vsts.release.yml
  release/createAdoPr.js
  release/fillReleaseNotesTemplate.js
  release/util.js
  releaseNote.md
  src/Misc/InstallAgentPackage.template.xml
  src/dev.sh
Labels: internal

#3519 Update VssApiVersion to 0.5.170-private
  src/Common.props
Labels: bug

#3518 Added info about job cancellation
  docs/design/jobcancellation.md
Labels: documentation, misc

#3526 Fixed error on finalize job (Could not load file or assembly 'Microsoft.VisualStudio.Services.Agent'...)
  src/Agent.Plugins/TestResultParser/ParserFactory.cs
Labels: bug

#3527 Add documentation for setting custom MTU parameter
  docs/design/setMTU.md
Labels: documentation, misc

#3529 Filling publish script with hashes
  .vsts.release.yml
  release/createAdoPrs.js
  release/package-lock.json
  release/package.json
  release/util.js
  src/Misc/Publish.template.ps1
Labels: enhancement, internal

#3528 Installing dependencies for SUSE systems - fixed issue with incorrect ID parameter picking up
  src/Misc/layoutbin/installdependencies.sh
Labels: bug

#3536 dotnet-install.sh updating
  src/Misc/dotnet-install.sh
Labels: misc

#3538 Update ubuntu image in the CI
  .azure-pipelines/pipeline.yml
Labels: internal

#3534 Add prompt for autostarting service on Windows
  src/Agent.Listener/CommandLine/ConfigureAgent.cs
  src/Agent.Listener/CommandSettings.cs
  src/Agent.Listener/Configuration.Windows/WindowsServiceControlManager.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement

#3533 Add support of the default AdoptOpenJDK registry keys to capabilities scanner
  src/Misc/layoutbin/powershell/Add-JavaCapabilities.ps1
  src/Misc/layoutbin/powershell/CapabilityHelpers/CapabilityFunctions.ps1
Labels: bug

#3539 Add retries to client create and GetPipelineCacheArtifactAsync
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
Labels: bug

#3543 Update image deprecation script for upcoming deprecations
  tools/FindPipelinesUsingRetiredImages/QueryJobHistoryForRetiredImages.ps1
  tools/FindPipelinesUsingRetiredImages/readme.md
Labels: enhancement
