Repository microsoft/azure-pipelines-agent, pull requests merged in 2021-03, with the labels that each got.

#3282 Implemented a knob to allow TFVC unshelve command errors
  src/Agent.Plugins/TfsVCSourceProvider.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
Labels: enhancement

#3290 Update of NodeJS tool version to 10.24.0 #3289
  src/Misc/externals.sh
Labels: Area: Agent, dependencies, enhancement

#3296 Revert "Self-hosted agent cleaning source folder (#3237)"
  releaseNote.md
  src/Agent.Worker/Build/BuildDirectoryManager.cs
  src/Agent.Worker/PluginInternalCommandExtension.cs
  src/agentversion
Labels: bug

#3298 Revert "Self-hosted agent cleaning source folder (#3237)"
  releaseNote.md
  src/Agent.Worker/Build/BuildDirectoryManager.cs
  src/Agent.Worker/PluginInternalCommandExtension.cs
  src/agentversion
Labels: bug

#3300 Work around missing PowerShell profile
  .vsts.release.yml
Labels: internal

#3301 Change CI defaults
  .vsts.ci.yml
Labels: internal

#3279 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20210222210717617 to Localization
  Localize/loc/zh-TW/src/Agent.Service/Windows/Resource.resx.lcl
Labels: enhancement

#3303 Decode %AZP25 to % by default
  src/Agent.Sdk/Knob/AgentKnobs.cs
Labels: enhancement

#3306 Remove broken myget feeds
  src/Agent.Listener/NuGet.Config
  src/Agent.Worker/NuGet.Config
  src/Microsoft.VisualStudio.Services.Agent/NuGet.Config
  src/NuGet.Config
  src/Test/NuGet.Config
Labels: internal

#3313 Fix the triggering build logic for Download Pipeline Artifact
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV2.cs
Labels: bug

#3324 Fixed notification for the localization pipeline
  open-pullrequest.ps1
Labels: internal

#3322 [PR script] Added automatic label setting
  open-pullrequest.ps1
Labels: internal

#3269 Set up schedule and notifications for the localization pipeline
  Localize/localize-pipeline.yml
  open-pullrequest.ps1
Labels: internal

#3297 Revert "Self-hosted agent cleaning source folder (#3237)"
  src/Agent.Worker/Build/BuildDirectoryManager.cs
  src/Agent.Worker/PluginInternalCommandExtension.cs
Labels: bug

#3332 Fixed localization pipeline issue with already localized strings replaced
  Localize/localize-pipeline.yml
Labels: internal

#3329 Introduce enforcement mode for task restrictions
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/JobExtension.cs
  src/Agent.Worker/TaskCommandExtension.cs
  src/Agent.Worker/TaskManager.cs
  src/Agent.Worker/TaskRestrictionsChecker.cs
  src/Agent.Worker/TaskRestrictionsExtension.cs
  src/Agent.Worker/Telemetry/TelemetryCommandExtension.cs
  src/Agent.Worker/WorkerCommandManager.cs
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L0/ServiceInterfacesL0.cs
  src/Test/L0/Worker/CodeCoverage/CodeCoverageCommandExtensionTests.cs
  src/Test/L0/Worker/SetVariableRestrictionsL0.cs
  src/Test/L0/Worker/TaskCommandExtensionL0.cs
  src/Test/L0/Worker/Telemetry/TelemetryCommandExtensionTests.cs
  src/Test/L0/Worker/TestResults/ResultsCommandExtensionTests.cs
Labels: enhancement

#3299 Add plugin for DownloadBuildArtifactsV1
  src/Agent.Plugins/Artifact/ArtifactDownloadParameters.cs
  src/Agent.Plugins/Artifact/ArtifactProviderFactory.cs
  src/Agent.Plugins/Artifact/BuildServer.cs
  src/Agent.Plugins/Artifact/FileContainerProvider.cs
  src/Agent.Plugins/Artifact/FileShareProvider.cs
  src/Agent.Plugins/Artifact/IArtifactProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactConstants.cs
  src/Agent.Plugins/Artifact/PipelineArtifactProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactServer.cs
  src/Agent.Plugins/BuildArtifact/BuildArtifactPluginConstants.cs
  src/Agent.Plugins/BuildArtifact/BuildArtifactPluginV1.cs
  src/Agent.Plugins/PipelineArtifact/FileContainerProvider.cs
  src/Agent.Plugins/PipelineArtifact/IArtifactProvider.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV1.cs
  src/Agent.Sdk/Blob/DedupManifestArtifactClientFactory.cs
  src/Agent.Worker/AgentPluginManager.cs
  src/Agent.Worker/Build/FileContainerServer.cs
  src/Common.props
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
  src/Test/L0/Plugin/TestFileShareProvider/TestFileShareProviderL0.cs
Labels: enhancement

#3331 Git version update to solved vulnulability #3325
  src/Misc/externals.sh
Labels: Area: Agent, dependencies, enhancement

#3340 fix agent version & release notes
  releaseNote.md
  src/agentversion
Labels: internal

#3341 Use AME deployment pool for releases
  .vsts.release.yml
Labels: internal

#3338 Add more logging for download pipeline artifact task
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV2.cs
Labels: enhancement

#3347 Release 2.184.2 hotfix PR
  releaseNote.md
  src/Misc/externals.sh
  src/agentversion
Labels: internal

#3345 Upload timeline attachments to blob-backed FCS
  src/Agent.Plugins/Agent.Plugins.csproj
  src/Agent.Plugins/Artifact/FileContainerProvider.cs
  src/Agent.Plugins/Artifact/FileShareProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactServer.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
  src/Agent.Worker/Build/FileContainerServer.cs
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobStoreUtils.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/TimelineRecordAttachmentTelemetryRecord.cs
  src/Microsoft.VisualStudio.Services.Agent/JobServer.cs
  src/Microsoft.VisualStudio.Services.Agent/JobServerQueue.cs
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
  src/Test/L0/Plugin/TestFileShareProvider/TestFileShareProviderL0.cs
  src/Test/L1/Mock/FakeJobServer.cs
Labels: enhancement
