Repository microsoft/azure-pipelines-agent, pull requests merged in 2021-08, with the labels that each got.

#3485 Updating vss-api-nuget package - fix blobstore client header length exceeds limits
  src/Common.props
Labels: bug

#3496 Fix typo
  src/Agent.Listener/Agent.cs
Labels: misc

#3493 Added processing of NO_PROXY variable
  src/Microsoft.VisualStudio.Services.Agent/VstsAgentWebProxy.cs
  src/Test/L0/VstsAgentWebProxyL0.cs
Labels: bug

#3497 [AgentService] Fix invalid argument passing on reruns
  src/Misc/layoutbin/AgentService.js
Labels: bug

#3500 Allow to specify MTU value for networks used by container jobs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Container/DockerCommandManager.cs
Labels: enhancement, Area: Agent

#3507 Fixed issue with installing dependencies for suse systems
  src/Misc/layoutbin/installdependencies.sh
Labels: bug

#3467 [DownloadBuildArtifactsV1] Tar extraction on download
  src/Agent.Plugins/Artifact/ArtifactDownloadParameters.cs
  src/Agent.Plugins/Artifact/FileContainerProvider.cs
  src/Agent.Plugins/BuildArtifact/BuildArtifactPluginV1.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement

#3510 Fixed typo - installdependencies.sh
  src/Misc/layoutbin/installdependencies.sh
Labels: bug

#3513 Update dotnet-install.ps1 to the latest to fix tests
  src/Misc/dotnet-install.ps1
Labels: internal

#3512 Remove task restriction feature flags and telemetry
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/TaskRestrictionsChecker.cs
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L0/Worker/SetVariableRestrictionsL0.cs
Labels: internal
