Repository microsoft/azure-pipelines-agent, pull requests merged in 2021-10, with the labels that each got.

#3544 Add prune-tags parameter to fetch
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/GitCommandManager.cs
Labels: enhancement

#3548 Summarized view of Xunit hierarchal tests based on a FF
  src/Agent.Worker/TestResults/Parser.cs
  src/Agent.Worker/TestResults/Utils/FeatureFlagService.cs
  src/Agent.Worker/TestResults/Utils/TestResultsConstants.cs
  src/Test/L0/Worker/TestResults/ParserTests.cs
Labels: enhancement

#3551 Createa agent hotfix 2.193.1
  releaseNote.md
  src/Agent.Worker/TestResults/Parser.cs
  src/Agent.Worker/TestResults/Utils/FeatureFlagService.cs
  src/Agent.Worker/TestResults/Utils/TestResultsConstants.cs
  src/Test/L0/Worker/TestResults/ParserTests.cs
  src/agentversion
Labels: internal

#3524 Validate agent package checksum during self-update
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/SelfUpdater.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/IOUtil.cs
  src/Agent.Sdk/Util/StringUtil.cs
  src/Microsoft.VisualStudio.Services.Agent/Util/ServerUtil.cs
Labels: enhancement

#3555 Improve the ArgumentException message for changing file attributes
  src/Agent.Sdk/Util/IOUtil.cs
Labels: misc

#3505 Add the ability to retry the pipeline task if execution failed
  src/Agent.Listener/DistributedTask.Pipelines/Yaml/Contracts/DeploymentTarget.cs
  src/Agent.Listener/DistributedTask.Pipelines/Yaml/Contracts/TaskStep.cs
  src/Agent.Listener/DistributedTask.Pipelines/Yaml/TypeConverters/ConverterUtil.phases.cs
  src/Agent.Listener/DistributedTask.Pipelines/Yaml/TypeConverters/YamlConstants.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/Handlers/PowerShell3Handler.cs
  src/Agent.Worker/RetryHelper.cs
  src/Agent.Worker/TaskRunner.cs
  src/Common.props
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement

#3550 Add processing of target inputs in decorator task
  src/Agent.Worker/TaskDecoratorManager.cs
  src/Agent.Worker/TaskRunner.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement
