Repository microsoft/azure-pipelines-agent, pull requests merged in 2022-12, with the labels that each got.

#4013 Not mask tasks banner
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/TaskRunner.cs
  src/Test/L0/Worker/Build/GitSourceProviderL0.cs
  src/Test/L0/Worker/Build/TfsVCSourceProvider.WorkspaceUtilL0.cs
  src/Test/L0/Worker/CodeCoverage/CodeCoverageUtilitiesTests.cs
  src/Test/L0/Worker/TestResults/ParserTests.cs
Labels: enhancement

#4066 Add logic to notify customer in pipeline run about an agent is running on system not supporting .NET 6
  src/Agent.Listener/SelfUpdater.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/ExecutionContext.cs
Labels: enhancement

#4071 Change PowerShell ExecutionPolicy to RemoteSigned
  src/Agent.Worker/DiagnosticLogManager.cs
  src/Microsoft.VisualStudio.Services.Agent/Capabilities/PowerShellCapabilitiesProvider.cs
Labels: misc

#4077 honor VSO_DEDUP_REDIRECT_TIMEOUT_IN_SEC
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
Labels: bug

#4073 Implement AZP_IGNORE_SECRETS_SHORTER_THAN knob
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.Listener/Configuration/CredentialProvider.cs
  src/Agent.Listener/Program.cs
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/LoggedSecretMasker.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/Release/ContainerProvider/Helpers/VssConnectionFactory.cs
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
  src/Test/L0/Listener/Configuration/AgentCredentialL0.cs
  src/Test/L0/SecretMaskerTests/LoggedSecretMaskerL0.cs
  src/dev.sh
Labels: enhancement

#4074 Fix for agent hang when process cannot be killed
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.Sdk/AssemblyInfo.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/ProcessInvoker.MacLinux.cs
  src/Agent.Sdk/ProcessInvoker.Windows.cs
  src/Agent.Sdk/ProcessInvoker.cs
  src/Agent.Worker/AgentLogPlugin.cs
  src/Agent.Worker/Handlers/Handler.cs
  src/Agent.Worker/Handlers/HandlerFactory.cs
  src/Agent.Worker/Handlers/LegacyPowerShellHandler.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/Handlers/PowerShell3Handler.cs
  src/Agent.Worker/Handlers/PowerShellExeHandler.cs
  src/Agent.Worker/Handlers/ProcessHandler.cs
  src/Agent.Worker/Handlers/StepHost.cs
  src/Agent.Worker/StepsRunner.cs
  src/Microsoft.VisualStudio.Services.Agent/ProcessInvoker.cs
  src/Test/L0/ProcessInvokerL0.cs
Labels: bug

#4082 Catch agent updating exception
  src/Agent.Listener/Agent.cs
Labels: bug

#4084 Update Node16 to 16.17.1 version
  src/Misc/externals.sh
Labels: enhancement

#4079 Bump ubuntu image version to 20.04
  .azure-pipelines/pipeline.yml
  .vsts.release.yml
Labels: misc, DevOps

#3788 Prevent creating host container network
  src/Agent.Worker/ContainerOperationProvider.cs
Labels: bug

#3339 Allow env.sh to accept additional env var names
  src/Misc/layoutroot/env.sh
Labels: enhancement

#4088 Revert "Fix execution of scripts in variables (#4016)"
  src/Agent.Worker/TaskRunner.cs
  src/Agent.Worker/Variables.cs
  src/Agent.Worker/WorkerUtilties.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/EnvVariableParts.cs
  src/Microsoft.VisualStudio.Services.Agent/Util/VarUtil.cs
  src/Test/L0/Util/VarUtilL0.cs
  src/Test/L0/Worker/VariablesL0.cs
Labels: bug

#3943 Add Ubuntu 18.04 to QueryJobHistoryForRetiredImages.ps1
  tools/FindPipelinesUsingRetiredImages/QueryJobHistoryForRetiredImages.ps1
  tools/FindPipelinesUsingRetiredImages/readme.md
Labels: internal

#4081 Make agent update list of systems supporting .NET 6 periodically
  src/Agent.Listener/SelfUpdater.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/JobRunner.cs
Labels: enhancement

#4085 Retries to lock Services database
  src/Agent.Listener/Configuration.Windows/NativeWindowsServiceHelper.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: misc

#3888 Fixed name of DockerAdditionalNetworkOptions Knob
  src/Agent.Sdk/Knob/AgentKnobs.cs
Labels: bug
