Repository microsoft/azure-pipelines-agent, pull requests merged in 2022-09, with the labels that each got.

#3958 Update Agent.Worker GitSourceProvider to not pass auth header in arguments
  src/Agent.Worker/Build/GitSourceProvider.cs
Labels: bug

#3960 Update dotnet-install.sh scripts
  src/Misc/dotnet-install.sh
Labels: misc, Area: Agent

#3941 Updated Agent.Worker.csproj such that a new version of System.Security.Cryptography.ProtectedData can be used for Azure.Identity
  src/Agent.Worker/Agent.Worker.csproj
Labels: misc

#3963 Remove Debugger.Launch from Test_Base_Node10
  src/Test/L1/Worker/CoreL1Tests.cs
Labels: bug

#3947 Include 'git status' as part of system diagnostics when debugging a pipeline
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Worker/Build/GitCommandManager.cs
  src/Agent.Worker/Build/GitSourceProvider.cs
Labels: enhancement

#3969 Pass oauth token for tf.exe utility securely to avoid it being logged in OS
  src/Agent.Plugins/TfsVCCliManager.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/TfsVCCommandManager.cs
Labels: internal

#3970 Introduce gMSA accounts support
  src/Agent.Listener/Configuration.Windows/NativeWindowsServiceHelper.cs
  src/Agent.Listener/Configuration.Windows/WindowsServiceControlManager.cs
  src/Agent.Listener/Configuration/Validators.cs
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L0/Listener/Configuration/Mocks/MockNativeWindowsServiceHelper.cs
  src/Test/L0/Listener/Configuration/NativeWindowsServiceHelperL0.cs
Labels: enhancement

#3955 Implement getting knob value by source type
  src/Agent.Sdk/Knob/BuiltInDefaultKnobSource.cs
  src/Agent.Sdk/Knob/CompositeKnobSource.cs
  src/Agent.Sdk/Knob/ICompositeKnobSource.cs
  src/Agent.Sdk/Knob/IKnobSource.cs
  src/Agent.Sdk/Knob/IKnobValueContext.cs
  src/Agent.Sdk/Knob/Knob.cs
  src/Agent.Sdk/Knob/KnobValue.cs
  src/Agent.Sdk/Knob/RuntimeKnobSource.cs
  src/Test/L0/KnobL0.cs
Labels: enhancement
