Repository microsoft/azure-pipelines-agent, pull requests merged in 2022-06, with the labels that each got.

#3845 Added message - in case when account is not managed, but WindowsLogon…
  src/Agent.Listener/Configuration.Windows/WindowsServiceControlManager.cs
Labels: enhancement

#3856 Updated the link to the hosted images repositiry in issue template
  .github/ISSUE_TEMPLATE.md
Labels: misc, Area: Agent

#3857 Improve retry logic for downloading tasks
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/TaskManager.cs
Labels: enhancement

#3867 [Agent CI] Update signing pipeline to respect the new MinGit layout
  .azure-pipelines/signing.yml
Labels: misc, Area: ABTT

#3868 [Agent CI] Improve release pipeline stability
  .azure-pipelines/build-jobs.yml
  .azure-pipelines/signing.yml
Labels: misc

#3871 Add ability to specify domainId for creating dedupmanifestartifactclient
  src/Agent.Plugins/Artifact/FileShareProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactServer.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
Labels: enhancement

#3881 update install-dotnet scripts to latest version
  src/Misc/dotnet-install.ps1
  src/Misc/dotnet-install.sh
Labels: internal, Area: Agent

#3883 Revert changes related to gMSA account support
  src/Agent.Listener/Configuration.Windows/NativeWindowsServiceHelper.cs
  src/Agent.Listener/Configuration.Windows/WindowsServiceControlManager.cs
  src/Test/L0/Listener/Configuration/Mocks/MockNativeWindowsServiceHelper.cs
  src/Test/L0/Listener/Configuration/NativeWindowsServiceHelperL0.cs
Labels: bug
