Repository microsoft/azure-pipelines-agent, pull requests merged in 2022-11, with the labels that each got.

#4010 Migration powershell script of release pipeline for Az 1.0.0
  .vsts.release.yml
Labels: bug

#3992 [Bug 1942506](P2): [Pipelines]: PAT invalid in auto-generated PowerShell script for add VM resource in New Environment in ADO Server #3561
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/Configuration/ConfigurationProvider.cs
  src/Microsoft.VisualStudio.Services.Agent/AgentCertificateManager.cs
  src/Microsoft.VisualStudio.Services.Agent/VstsAgentWebProxy.cs
Labels: bug

#4021 Include strings from Misc/src/layoutbin to LocProject file
  Localize/LocProject.json
Labels: internal

#4020 Rhel 6 add node10 fallback
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Test/L0/NodeHandlerL0.cs
Labels: bug

#4018 Fixed NullReferenceException in v3.212.0 preview version Agent
  src/Agent.Worker/TaskRunner.cs
Labels: bug

#4024 Fix vsts release conditions
  .vsts.release.yml
Labels: misc

#4026 Upload to Azure Blob - remove condition
  .vsts.release.yml
Labels: misc

#4030 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20221104175414554 to Localization
  Localize/loc/de-DE/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/es-ES/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/fr-FR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/it-IT/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ja-JP/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ko-KR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ru-RU/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-CN/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-TW/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement

#4031 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20221105085259861 to Localization
  Localize/loc/de-DE/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/es-ES/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/fr-FR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/it-IT/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ja-JP/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ko-KR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ru-RU/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-CN/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-TW/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement

#4032 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20221106085521421 to Localization
  Localize/loc/de-DE/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/es-ES/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/fr-FR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/it-IT/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ko-KR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ru-RU/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-CN/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-TW/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement

#4040 Revert "Implement AGENT_MIN_SECRET_LENGTH knob (#3962)"
  src/Agent.Listener/Configuration/CredentialProvider.cs
  src/Agent.Listener/Program.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/LoggedSecretMasker.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/Release/ContainerProvider/Helpers/VssConnectionFactory.cs
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
  src/Test/L0/Listener/Configuration/AgentCredentialL0.cs
  src/Test/L0/SecretMaskerTests/LoggedSecretMaskerL0.cs
Labels: bug

#4046 Update dotnet scripts
  src/Misc/dotnet-install.ps1
  src/Misc/dotnet-install.sh
Labels: misc, Area: Agent

#4038 Release pipeline fail on Azure Git repo with LFS
  src/Agent.Worker/Build/GitCommandManager.cs
  src/Agent.Worker/Build/GitSourceProvider.cs
  src/Test/L0/Worker/Build/GitSourceProviderL0.cs
Labels: bug

#4053 Add null & empty check for DeactivateVsoCommands
  src/Agent.Sdk/Util/StringUtil.cs
  src/Agent.Worker/WorkerUtilties.cs
  src/Test/L0/Util/StringUtilL0.cs
  src/Test/L0/Worker/WorkerL0.cs
Labels: bug

#4056 Update dotnet-install scripts
  src/Misc/dotnet-install.ps1
  src/Misc/dotnet-install.sh
Labels: misc

#4052 Added tool converting str to env variable format
  .azure-pipelines/build-job.yml
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Worker/Build/GitCommandManager.cs
  src/Agent.Worker/Handlers/Handler.cs
  src/Agent.Worker/Handlers/PowerShellExeHandler.cs
  src/Agent.Worker/Release/AgentUtilities.cs
  src/Microsoft.VisualStudio.Services.Agent/Util/VarUtil.cs
  src/Test/L0/Util/VarUtilL0.cs
Labels: enhancement

#3944 MSI connection set up for Azure Container Registry for Container Jobs
  src/Agent.Worker/Agent.Worker.csproj
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Test/L0/Worker/JobExtensionL0.cs
  src/Test/L0/Worker/JobRunnerL0.cs
Labels: enhancement

#4048 Add release variables for vso commands deactivating dictionary
  src/Agent.Worker/Variables.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Test/L0/Worker/WorkerL0.cs
Labels: enhancement

#4042 [Refactor] Move launch of msbuild to function
  src/dev.sh
Labels: misc

#4016 Fix execution of scripts in variables
  src/Agent.Worker/TaskRunner.cs
  src/Agent.Worker/Variables.cs
  src/Agent.Worker/WorkerUtilties.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/EnvVariableParts.cs
  src/Microsoft.VisualStudio.Services.Agent/Util/VarUtil.cs
  src/Test/L0/Util/VarUtilL0.cs
  src/Test/L0/Worker/VariablesL0.cs
Labels: enhancement

#4041 Run task on next available Node version, if targeted version is not available
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Test/L0/NodeHandlerL0.cs
Labels: enhancement

#4068 Update dotnet6-agent branch from master
  .azure-pipelines/build-job.yml
  .vsts.release.yml
  release/package-lock.json
  release/package.json
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/Configuration/ConfigurationProvider.cs
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/ProcessInvoker.cs
  src/Agent.Sdk/Util/StringUtil.cs
  src/Agent.Worker/Agent.Worker.csproj
  src/Agent.Worker/Build/GitCommandManager.cs
  src/Agent.Worker/Build/GitSourceProvider.cs
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Agent.Worker/Handlers/Handler.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/Handlers/PowerShellExeHandler.cs
  src/Agent.Worker/Release/AgentUtilities.cs
  src/Agent.Worker/Variables.cs
  src/Agent.Worker/Worker.cs
  src/Agent.Worker/WorkerUtilties.cs
  src/Microsoft.VisualStudio.Services.Agent/AgentCertificateManager.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/Util/VarUtil.cs
  src/Microsoft.VisualStudio.Services.Agent/VstsAgentWebProxy.cs
  src/Misc/dotnet-install.ps1
  src/Misc/dotnet-install.sh
  src/Misc/externals.sh
  src/Misc/layoutbin/de-DE/strings.json
  src/Misc/layoutbin/es-ES/strings.json
  src/Misc/layoutbin/fr-FR/strings.json
  src/Misc/layoutbin/it-IT/strings.json
  src/Misc/layoutbin/ja-JP/strings.json
  src/Misc/layoutbin/ko-KR/strings.json
  src/Misc/layoutbin/ru-RU/strings.json
  src/Misc/layoutbin/zh-CN/strings.json
  src/Misc/layoutbin/zh-TW/strings.json
  src/Test/L0/NodeHandlerL0.cs
  src/Test/L0/Util/StringUtilL0.cs
  src/Test/L0/Util/VarUtilL0.cs
  src/Test/L0/Worker/Build/GitSourceProviderL0.cs
  src/Test/L0/Worker/JobExtensionL0.cs
  src/Test/L0/Worker/JobRunnerL0.cs
  src/Test/L0/Worker/WorkerL0.cs
  src/dev.sh
Labels: internal, Area: Agent

#4064 Update .NET 3.1 Agent to never upgrade to .NET 6 on unsupported OS
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.Listener/SelfUpdater.cs
  src/Agent.Listener/net6.json
  src/Agent.Sdk/Util/PlatformUtil.cs
Labels: enhancement
