Repository microsoft/azure-pipelines-agent, pull requests merged in 2022-07, with the labels that each got.

#3861 Added node16 execution handler
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/TaskManager.cs
  src/Misc/externals.sh
  src/Test/L0/NodeHandlerL0.cs
  src/Test/L0/Worker/TaskManagerL0.cs
Labels: enhancement

#3890 Fix vulnerabilities in labelchecker
  .github/labelChecker/package-lock.json
  .github/labelChecker/package.json
Labels: misc, dependencies

#3897 remove npx in the node 10 directory; remove npm, npx, corepack, and related node modules in the node 16 directory
  src/Misc/externals.sh
Labels: misc

#3899 Patch for Agent v2.206.0 - `Node 16` execution handler & Remove unused folders from Node distribution
  releaseNote.md
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/TaskManager.cs
  src/Misc/dotnet-install.ps1
  src/Misc/dotnet-install.sh
  src/Misc/externals.sh
  src/Test/L0/NodeHandlerL0.cs
  src/Test/L0/Worker/TaskManagerL0.cs
  src/agentversion
Labels: bug

#3880 Maintenance job - make maintenance operation for source provider independent on build directory clean up time interval
  src/Agent.Worker/Build/WorkspaceMaintenanceProvider.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Test/L0/Worker/Build/WorkspaceMaintenanceProvicerL0.cs
Labels: bug, Area: Agent

#3893 AZP_AGENT_USE_LEGACY_HTTP knob: added warning and announcement
  README.md
  src/Agent.Listener/Program.cs
Labels: misc, Area: Agent

#3904 [CG alert] Update guid for l1Task CmdLine Node10
  src/Misc/externals.sh
  src/Test/L1/Worker/L1TestBase.cs
Labels: bug

#3920 Remove redundant 'Newtonsoft.JSON' declaration
  src/Agent.Listener/Agent.Listener.csproj
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
Labels: internal, dependencies

#3924 Update dotnet install script
  src/Misc/dotnet-install.ps1
Labels: internal
