Repository microsoft/azure-pipelines-agent, pull requests merged in 2022-08, with the labels that each got.

#3923 Add centos 7.9 image
  images/centos7/Dockerfile
  images/readme.md
Labels: internal, Area: Agent

#3927 Update vmImage to macos-11 and disable falling tests
  .azure-pipelines/pipeline.yml
  src/Test/L0/ProcessExtensionL0.cs
  src/Test/L0/ProcessInvokerL0.cs
Labels: internal, Area: Agent

#3907 consume fetchTags signal
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Worker/Build/GitCommandManager.cs
  src/Agent.Worker/Build/GitSourceProvider.cs
  src/Common.props
  src/Test/L0/Worker/Build/GitSourceProviderL0.cs
Labels: enhancement, dependencies

#3925 Changed script path creation logic
  release/createAdoPrs.js
Labels: internal

#3934 Update dotnet install script
  src/Misc/dotnet-install.ps1
Labels: misc

#3902 Check in the agent CI if broken symlinks exist in the agent build
  .azure-pipelines/build-job.yml
  src/Misc/check-symlinks.sh
Labels: misc

#3921 Fix agent build script
  src/dev.sh
Labels: misc

#3939 Added information message if agent with same name already exist in pool
  src/Agent.Listener/Configuration/ConfigurationManager.cs
Labels: misc

#3837 Add group id matching user
  src/Agent.Sdk/ContainerInfo.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/ContainerOperationProvider.cs
Labels: bug, Area: Agent

#3933 [Repo config] Add `CODEOWNERS` file
  .github/CODEOWNERS
Labels: misc

#3946 Update dotnet-install.sh script
  src/Misc/dotnet-install.sh
Labels: misc

#3929 Changed node version to run as a service
  src/Misc/layoutbin/runsvc.sh
Labels: enhancement

#3949 Update GitSourceProvider to not pass auth header in arguments
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: bug
