Repository microsoft/azure-pipelines-agent, pull requests merged in 2022-05, with the labels that each got.

#3791 Added gMSA accounts support
  src/Agent.Listener/Configuration.Windows/NativeWindowsServiceHelper.cs
  src/Agent.Listener/Configuration.Windows/WindowsServiceControlManager.cs
  src/Test/L0/Listener/Configuration/Mocks/MockNativeWindowsServiceHelper.cs
  src/Test/L0/Listener/Configuration/NativeWindowsServiceHelperL0.cs
Labels: enhancement

#3827 Updating vss-api-netcore package
  src/Common.props
Labels: enhancement, Area: Core

#3793 Fix for "Azure DevOps Pipelines fails git with an HTTP 400 error"
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Plugins/GitSourceProvider.cs
Labels: bug

#3811 Update links in installdependencies.sh
  src/Misc/layoutbin/installdependencies.sh
Labels: bug, documentation

#3839 Bump git version to 2.36.1
  src/Misc/externals.sh
Labels: enhancement, dependencies

#3810 Fix event logs dumping
  src/Agent.Worker/DiagnosticLogManager.cs
Labels: misc

#3833 Removed NPM module and executable which comes with NodeJS fox non windows distribution
  src/Misc/externals.sh
Labels: internal, DevOps

#3795 Set sid service type as unrestricted - to make permissions for agent service more manageable
  src/Agent.Listener/CommandLine/ConfigureAgent.cs
  src/Agent.Listener/CommandSettings.cs
  src/Agent.Listener/Configuration.Windows/NativeWindowsServiceHelper.cs
  src/Agent.Listener/Configuration.Windows/WindowsServiceControlManager.cs
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Microsoft.VisualStudio.Services.Agent/ConfigurationStore.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement

#3785 Custom LFS server fix - reworked changes from PR#2706
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Sdk/TaskPlugin.cs
  src/Agent.Sdk/Util/ArgUtil/ArgUtil.cs
  src/Agent.Sdk/Util/ArgUtil/ArgUtilInstanced.cs
  src/Agent.Sdk/Util/ArgUtil/IArgUtilInstanced.cs
  src/Agent.Worker/Build/GitCommandManager.cs
  src/Test/L0/Plugin/TestGitCliManager/MockAgentTaskPluginExecutionContext.cs
  src/Test/L0/Plugin/TestGitCliManager/MockGitCliManager.cs
  src/Test/L0/Plugin/TestGitCliManager/TestGitCliManagerL0.cs
  src/Test/Test.csproj
Labels: bug

#3781 Update registry keys for AdoptOpenJDK
  src/Misc/layoutbin/powershell/Add-JavaCapabilities.ps1
Labels: enhancement

#3797 Users/flsaplac/diag folder location customisable
  src/Agent.Listener/Program.cs
  src/Agent.Listener/SelfUpdater.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/DiagnosticLogManager.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/Program.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Microsoft.VisualStudio.Services.Agent/Logging.cs
  src/Test/L0/HostContextL0.cs
  src/Test/L0/PagingLoggerL0.cs
  src/Test/L0/TestHostContext.cs
  src/Test/L1/L1HostContext.cs
  src/Test/L1/Worker/L1TestBase.cs
Labels: enhancement
