Repository microsoft/azure-pipelines-agent, pull requests merged in 2022-03, with the labels that each got.

#3764 Fix TEE download error when agent and work directory are located on different mounts
  src/Agent.Sdk/Util/TeeUtil.cs
Labels: bug

#3768 Use cancellation token everywhere in TeeUtil
  src/Agent.Sdk/Util/TeeUtil.cs
Labels: enhancement

#3775 Update info about legacy http handler
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Knob/Knob.cs
  src/Agent.Worker/JobExtension.cs
Labels: enhancement

#3772 Migrate to Ubuntu X64 for ARM build
  .azure-pipelines/build-job.yml
  .azure-pipelines/pipeline.yml
Labels: misc

#3744 Move notifications about Agent Localization PR from Slack to MS Teams - Part 1
  Localize/localize-pipeline.yml
  open-pullrequest.ps1
  send-notifications.ps1
Labels: enhancement

#3745 Move notifications about Agent Localization PR from Slack to MS Teams - Part 2
  open-pullrequest.ps1
  send-notifications.ps1
Labels: enhancement

#3786 Update the `src/Misc/dotnet-install.sh` file
  src/Misc/dotnet-install.sh
Labels: misc
