Repository microsoft/azure-pipelines-agent, pull requests merged in 2022-02, with the labels that each got.

#3726 Change release x86 build image back to windows-2019
  .azure-pipelines/pipeline.yml
Labels: bug

#3557 Separate email and user in publish script
  .vsts.release.yml
  release/createAdoPrs.js
Labels: enhancement

#3730 Add correction of empty Matching pattern field to default value
  src/Agent.Plugins/BuildArtifact/BuildArtifactPluginV1.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV1.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV2.cs
Labels: bug

#3732 Corrected condition for check value in itemPattern
  src/Agent.Plugins/BuildArtifact/BuildArtifactPluginV1.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV1.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV2.cs
Labels: bug

#3731 Patch for Agent v2.198.2 - Added correction of empty Matching pattern field in DownloadBuildArtifact and DownloadPipelineArtifact tasks
  .azure-pipelines/pipeline.yml
  releaseNote.md
  src/Agent.Plugins/BuildArtifact/BuildArtifactPluginV1.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV1.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV2.cs
  src/agentversion
Labels: bug

#3734 Changed image for stage Windows (x86) to windows-2019
  .azure-pipelines/pipeline.yml
Labels: bug

#3738 Add check the support of custom server certificate validation
  src/Agent.Sdk/Util/VssUtil.cs
Labels: bug

#3741 Update error message on PR changes #3738
  src/Agent.Sdk/Util/VssUtil.cs
Labels: enhancement

#3743 Migrate ARM64 build to 1es pool
  .azure-pipelines/build-job.yml
  .azure-pipelines/pipeline.yml
Labels: misc

#3749 Release scripts - npm audit fix
  release/package-lock.json
  release/package.json
Labels: misc

#3748 Add some logging to the ProcessInvoker
  src/Agent.Sdk/ProcessInvoker.cs
  src/Agent.Worker/Handlers/StepHost.cs
  src/Misc/layoutbin/containerHandlerInvoker.js.template
Labels: enhancement

#3760 Turned on x86 pool for ci checks
  .vsts.ci.yml
Labels: misc

#3747 Fix error message in case of missing debsums
  src/Agent.Worker/DiagnosticLogManager.cs
Labels: enhancement

#3763 Update VssApiClient version to 0.5.173-private
  src/Common.props
Labels: bug

#3765 Release 2.200.2 hotfix PR
  releaseNote.md
  src/Common.props
  src/Misc/dotnet-install.ps1
  src/agentversion
Labels: internal

#3766 Add dotnet 2.1 installation before signing
  .azure-pipelines/build-job.yml
Labels: internal

#3762 Fix null ref exception for in IsInjectedTaskForTarget method for TFS 2017 and earlier
  src/Agent.Worker/TaskDecoratorManager.cs
  src/Agent.Worker/TaskRunner.cs
  src/Test/L0/Worker/TaskDecoratorManagerL0.cs
Labels: bug
