Repository microsoft/azure-pipelines-agent, pull requests merged in 2022-01, with the labels that each got.

#3682 Added masking for environment variables containing credentials in diagnostic logs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Knob/CompositeKnobSource.cs
  src/Agent.Sdk/Knob/EnvironmentKnobSource.cs
  src/Agent.Sdk/Knob/ICompositeKnobSource.cs
  src/Agent.Sdk/Knob/IEnvironmentKnobSource.cs
  src/Agent.Sdk/Knob/Knob.cs
  src/Agent.Worker/JobExtension.cs
  src/Microsoft.VisualStudio.Services.Agent/Capabilities/EnvironmentCapabilitiesProvider.cs
Labels: enhancement

#3680 Add function to read waagent.conf settings and condition to run it only on Linux
  src/Agent.Worker/DiagnosticLogManager.cs
Labels: enhancement

#3697 Switched macos pool to 10.15
  .azure-pipelines/pipeline.yml
Labels: misc

#3653 Add Event Log dumping
  src/Agent.Worker/DiagnosticLogManager.cs
Labels: enhancement

#3673 Add passive validation - list local group memberships
  src/Agent.Worker/DiagnosticLogManager.cs
  src/Misc/layoutbin/powershell/Get-LocalGroupMembership.ps1
Labels: enhancement

#3684 Download TEE plugin conditionally during checkout
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Plugins/RepositoryPlugin.cs
  src/Agent.Plugins/TfsVCSourceProvider.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/TeeUtil.cs
  src/Agent.Worker/Release/ReleaseJobExtension.cs
  src/Misc/externals.sh
  src/Misc/layoutroot/license.html
  src/Test/L0/TestHostContext.cs
  src/dir.proj
Labels: enhancement

#3690 Added information about user groups into environment file (Linux, MacOS)
  src/Agent.Worker/DiagnosticLogManager.cs
Labels: enhancement

#3695 Add info about labels Latest and Pre-release
  README.md
Labels: misc, Area: Agent

#3700 Add cloud-init logs to diagnostics archive
  src/Agent.Worker/DiagnosticLogManager.cs
Labels: enhancement

#3605 [macOS] Return the correct minor version on 11 and later OS.
  src/Microsoft.VisualStudio.Services.Agent/Capabilities/AgentCapabilitiesProvider.cs
Labels: enhancement

#3702 Added info about self-hosted case for manual testing
  src/Agent.Worker/Build/TrackingManager.cs
Labels: misc

#3704 [TEE download and removal logic] Fix permissions setting on MacOS
  src/Agent.Sdk/Util/TeeUtil.cs
Labels: bug

#3706 Update dumping waagent.conf file logic not to write waning on missed "waagent.conf"
  src/Agent.Worker/DiagnosticLogManager.cs
Labels: enhancement, Area: Agent

#3699 Don't allow a cache failure to fail builds
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
Labels: bug

#3707 Prepare release 2.198.1
  releaseNote.md
  src/Agent.Sdk/Util/TeeUtil.cs
  src/Agent.Worker/DiagnosticLogManager.cs
  src/agentversion
Labels: enhancement

#3709 Update dotnet-install script
  src/Misc/dotnet-install.ps1
  src/Misc/dotnet-install.sh
Labels: misc

#3698 Add simple support of Mariner OS distribution to installdependencies.sh
  src/Misc/layoutbin/installdependencies.sh
Labels: enhancement

#3710 Fix adding cloud-init logs to diagnostics archive
  src/Agent.Worker/DiagnosticLogManager.cs
Labels: bug

#3615 Allow specifying custom properties for PublishPipelineArtifact task
  src/Agent.Plugins/Artifact/PipelineArtifactConstants.cs
  src/Agent.Plugins/Artifact/PipelineArtifactServer.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPlugin.cs
  src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV1.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement

#3703 Dump Agent Azure VM extension logs
  src/Agent.Worker/DiagnosticLogManager.cs
Labels: enhancement

#3716 Update dotnet-install.sh script
  src/Misc/dotnet-install.sh
Labels: misc

#3714 Fix check for hosted agent
  src/Microsoft.VisualStudio.Services.Agent/ConfigurationStore.cs
Labels: bug

#3696 Added logging of origin of secrets
  .azure-pipelines/pipeline.yml
  src/Agent.Listener/CommandSettings.cs
  src/Agent.Sdk/Util/ILoggedSecretMasker.cs
  src/Agent.Sdk/Util/LoggedSecretMasker.cs
  src/Agent.Sdk/Util/WellKnownSecretAliases.cs
  src/Agent.Worker/Build/GitSourceProvider.cs
  src/Agent.Worker/JobExtension.cs
  src/Agent.Worker/TaskCommandExtension.cs
  src/Agent.Worker/Variables.cs
  src/Agent.Worker/Worker.cs
  src/Microsoft.VisualStudio.Services.Agent/AgentCertificateManager.cs
  src/Microsoft.VisualStudio.Services.Agent/Capabilities/EnvironmentCapabilitiesProvider.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Microsoft.VisualStudio.Services.Agent/Terminal.cs
  src/Microsoft.VisualStudio.Services.Agent/VstsAgentWebProxy.cs
  src/Test/L0/TestHostContext.cs
Labels: enhancement

#3712 [Passive validations] Check `debsums` output on Debian
  src/Agent.Worker/DiagnosticLogManager.cs
  src/Misc/layoutbin/installdependencies.sh
Labels: enhancement
