Repository microsoft/azure-pipelines-agent, pull requests merged in 2022-10, with the labels that each got.

#3981 Update image RHEL6 to RHEL7.2
  .azure-pipelines/build-job.yml
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
  README.md
  src/Misc/externals.sh
  src/Test/L0/ConstantGenerationL0.cs
  src/dev.sh
Labels: misc

#3986 Correct scripts in accordance with updating image RHEL6 to RHEL7.2
  .azure-pipelines/build-job.yml
  assets.json
  src/Common.props
  src/Misc/InstallAgentPackage.template.xml
  src/Misc/Publish.template.ps1
  src/Misc/PublishVSTSAgent.template.ps1
  src/Misc/UnpublishVSTSAgent.template.ps1
  src/Misc/externals.sh
  src/Test/L0/ConstantGenerationL0.cs
  src/dev.sh
Labels: misc

#3989 Revert all changes related to migration from RHEL6 to RHEL7
  .azure-pipelines/build-job.yml
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
  README.md
  assets.json
  releaseNote.md
  src/Common.props
  src/Misc/InstallAgentPackage.template.xml
  src/Misc/Publish.template.ps1
  src/Misc/PublishVSTSAgent.template.ps1
  src/Misc/UnpublishVSTSAgent.template.ps1
  src/Misc/externals.sh
  src/Test/L0/ConstantGenerationL0.cs
  src/dev.sh
Labels: misc

#3984 Added CloudId property to agent variables
  src/Agent.Worker/JobRunner.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
Labels: enhancement

#3973 FEATURE: Agent should gather telemetry on Task runner invocations
  src/Agent.Worker/TaskRunner.cs
Labels: enhancement

#3990 Add onlyGitHubRelease param for the release pipeline
  .vsts.release.yml
Labels: enhancement

#3879 Draft: Dotnet6 migration
  .azure-pipelines/build-job.yml
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
  src/Agent.Listener/Configuration.Windows/NativeWindowsServiceHelper.cs
  src/Agent.Listener/Configuration.Windows/WindowsServiceControlManager.cs
  src/Agent.Listener/NuGet.Config
  src/Agent.Plugins/TFCliManager.cs
  src/Agent.Plugins/TeeCliManager.cs
  src/Agent.Plugins/TfsVCCliManager.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/TFCommandManager.cs
  src/Agent.Worker/Build/TeeCommandManager.cs
  src/Agent.Worker/Build/TfsVCCommandManager.cs
  src/Agent.Worker/CodeCoverage/CodeCoverageCommands.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/Handlers/StepHost.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/WorkerCommandManager.cs
  src/Common.props
  src/Misc/dotnet-install.sh
  src/Misc/externals.sh
  src/Misc/layoutbin/installdependencies.sh
  src/Misc/layoutroot/config.sh
  src/Test/L0/ConstantGenerationL0.cs
  src/Test/L0/HostContextExtensionL0.cs
  src/Test/L0/Listener/AgentL0.cs
  src/Test/L0/Listener/Configuration/AgentCapabilitiesProviderTestL0.cs
  src/Test/L0/Listener/JobDispatcherL0.cs
  src/Test/L0/Plugin/ChunkerTests.cs
  src/Test/L0/Plugin/FingerprintCreatorTests.cs
  src/Test/L0/Plugin/LogPluginHostL0.cs
  src/Test/L0/Plugin/TestFileShareProvider/TestFileShareProviderL0.cs
  src/Test/L0/Plugin/TestResultParser/EnumerableExtensionL0.cs
  src/Test/L0/ProcessExtensionL0.cs
  src/Test/L0/TestHostContext.cs
  src/Test/L0/Util/IOUtilL0.cs
  src/Test/L1/Mock/FakeConfigurationStore.cs
  src/dev.sh
  tools/CredScanRegexes/readme.md
Labels: enhancement, Area: Agent

#3996 Avoid agent downgrading from 3.x to 2.x
  src/Agent.Listener/SelfUpdater.cs
Labels: misc

#3979 BUG 1972388: vsbuild task in YAML build pipeline hangs forever in ADO even though the task has already logged completion
  src/Agent.Worker/StepsRunner.cs
  src/Microsoft.VisualStudio.Services.Agent/JobServerQueue.cs
Labels: bug

#4001 Fix issues after conflict resolving for dotnet 6 issues
  src/Agent.Plugins/TfsVCCliManager.cs
  src/Agent.Worker/Build/TfsVCCommandManager.cs
  src/Agent.Worker/TaskRunner.cs
Labels: internal

#4000 Upgraded MinGit version to v2.38.1
  src/Misc/externals.sh
Labels: misc, Area: Agent

#3962 Implement AGENT_MIN_SECRET_LENGTH knob
  src/Agent.Listener/Configuration/CredentialProvider.cs
  src/Agent.Listener/Program.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/LoggedSecretMasker.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/Release/ContainerProvider/Helpers/VssConnectionFactory.cs
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
  src/Test/L0/Listener/Configuration/AgentCredentialL0.cs
  src/Test/L0/SecretMaskerTests/LoggedSecretMaskerL0.cs
Labels: enhancement

#3987 Fix vso commands execution in vulnerable variables
  src/Agent.Sdk/ProcessInvoker.cs
  src/Agent.Sdk/Util/StringUtil.cs
  src/Agent.Worker/Variables.cs
  src/Agent.Worker/Worker.cs
  src/Agent.Worker/WorkerUtilties.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Test/L0/Util/StringUtilL0.cs
  src/Test/L0/Worker/WorkerL0.cs
Labels: bug
