Repository microsoft/azure-pipelines-agent, pull requests merged in 2023-09, with the labels that each got.

#4408 Remove RHEL from the agent CI
  .azure-pipelines/build-job.yml
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
  .vsts.release.yml
  images/centos7/Dockerfile
  images/readme.md
  releaseNote.md
  src/Misc/externals.sh
  src/Misc/layoutroot/config.sh
  src/Test/L0/ConstantGenerationL0.cs
  src/dev.sh
Labels: misc

#4421 Update the `installdependencies.sh` script for Alpine
  src/Misc/layoutbin/installdependencies.sh
Labels: misc

#4416 Hiding deprecated vsts-task-lib
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
Labels: internal

#4429 Bump dotnet to 6.0.413 & node16 to 16.20.2
  .azure-pipelines/build-job.yml
  src/Common.props
  src/Misc/externals.sh
  src/dev.sh
Labels: misc

#4420 Remove not used "Microsoft.IdentityModel.Clients.ActiveDirectory"
  src/Agent.Listener/Agent.Listener.csproj
Labels: misc

#4415 Add ability to retrieve featureflag status
  src/Agent.Listener/Configuration/FeatureFlagProvider.cs
Labels: misc

#4356 Add default value if build repository clean is not set
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/BuildJobExtension.cs
Labels: enhancement, Area: ABTT, Area: Agent

#4441 Fix return type of GetFutureFlagAsync
  src/Agent.Listener/Configuration/FeatureFlagProvider.cs
Labels: bug

#4405 Add resource utilization metrics
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/ResourceMetricsManager.cs
  src/Test/L0/Worker/JobRunnerL0.cs
Labels: enhancement, Area: ABTT, Area: Agent

#4293 Fix release npm dependencies
  release/package-lock.json
  release/package.json
Labels: misc, dependencies

#4452 Revert "Update agents git to 2.41.0"
  src/Misc/externals.sh
Labels: bug

#4445 code changes to fix duplicate testresults
  src/Agent.Worker/TestResults/Legacy/TrxResultReader.cs
Labels: bug
