Repository microsoft/azure-pipelines-agent, pull requests merged in 2023-11, with the labels that each got.

#4501 Bump dotnet to 6.0.24
  .azure-pipelines/build-job.yml
  src/Common.props
  src/dev.sh
Labels: internal

#4504 dedupStoreHttpClient honors redirect timeout from client settings and update ADO lib to 0.5.227-262a3469
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.Plugins/Artifact/ArtifactItemFilters.cs
  src/Agent.Plugins/Artifact/FileContainerProvider.cs
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Worker/Agent.Worker.csproj
  src/Agent.Worker/Build/FileContainerServer.cs
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
  src/Microsoft.VisualStudio.Services.Agent/JobServer.cs
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
Labels: enhancement

#4495 Add SecretMasker implementation to the agent from core package
  src/Agent.Listener/Configuration/FeatureFlagProvider.cs
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/SecretMasking/ILoggedSecretMasker.cs
  src/Agent.Sdk/SecretMasking/ISecret.cs
  src/Agent.Sdk/SecretMasking/ISecretMasker.cs
  src/Agent.Sdk/SecretMasking/LegacyLoggedSecretMasker.cs
  src/Agent.Sdk/SecretMasking/LoggedSecretMasker.cs
  src/Agent.Sdk/SecretMasking/RegexSecret.cs
  src/Agent.Sdk/SecretMasking/ReplacementPosition.cs
  src/Agent.Sdk/SecretMasking/SecretMasker.cs
  src/Agent.Sdk/SecretMasking/ValueSecret.cs
  src/Agent.Worker/Variables.cs
  src/Agent.Worker/Worker.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Microsoft.VisualStudio.Services.Agent/TraceManager.cs
  src/Microsoft.VisualStudio.Services.Agent/Tracing.cs
  src/Test/L0/SecretMaskerTests/LoggedSecretMaskerL0.cs
  src/Test/L0/SecretMaskerTests/RegexSecretL0.cs
  src/Test/L0/SecretMaskerTests/SecretMaskerL0.cs
  src/Test/L0/TestHostContext.cs
Labels: internal

#4518 Replace node20 handler with node20_1
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/TaskManager.cs
  src/Misc/externals.sh
  src/Test/L0/NodeHandlerL0.cs
  src/Test/L0/Worker/TaskManagerL0.cs
Labels: internal

#4507 Check for task deprecation in runtime
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/TaskManager.cs
Labels: misc

#4520 Workaround to unblock Ubuntu 18 containers (fallback to Node16)
  src/Agent.Sdk/ContainerInfo.cs
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
Labels: misc

#4513 Fix UI redirection while resource usage exposes log
  src/Agent.Worker/ResourceMetricsManager.cs
  src/Agent.Worker/StepsRunner.cs
  src/Test/L0/Worker/StepsRunnerL0.cs
  src/Test/L1/Mock/FakeResourceMetricsManager.cs
  src/Test/L1/Worker/L1TestBase.cs
Labels: bug, Area: Agent

#4521 Remove VSTS-task-lib from agent
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
Labels: internal

#4526 Revert "Remove VSTS-task-lib from agent"
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
Labels: misc

#4524 For node20 fallback on host, check for glibc instead of OS version check
  src/Agent.Sdk/ContainerInfo.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/WorkerUtilties.cs
  src/Test/L0/NodeHandlerL0.cs
Labels: misc

#4528 Fix OSArchitecture for osx-arm64
  assets.json
  releaseNote.md
  src/Common.props
  src/Misc/Publish.template.ps1
Labels: misc

#4533 Fix skipsslvertificate option
  src/Agent.Listener/Configuration/FeatureFlagProvider.cs
  src/Agent.Listener/Telemetry/TelemetryPublisher.cs
Labels: bug

#4536 Fail Job When Agent dies
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/JobExtension.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/StepsRunner.cs
Labels: enhancement, Area: Agent

#4494 Update Node 20 version to the latest LTS (20.9.0) by @mmajcica
  src/Misc/externals.sh
Labels: misc, Area: Agent

#4525 Added release notifications
  .vsts.release.yml
  release/Send-PRsNotification.ps1
  release/createAdoPrs.js
Labels: misc

#4534 Update azure-identity package to 1.10.2
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.Worker/Agent.Worker.csproj
Labels: internal

#4540 remove extra nuget feed sources
  src/Agent.Listener/NuGet.Config
Labels: misc
