Repository microsoft/azure-pipelines-agent, pull requests merged in 2023-10, with the labels that each got.

#4424 Fixed file name truncating when file is located in the root of the disk
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/FileContainerServer.cs
Labels: bug, Area: Agent

#4454 Localization update
  src/Misc/layoutbin/de-DE/strings.json
  src/Misc/layoutbin/es-ES/strings.json
  src/Misc/layoutbin/fr-FR/strings.json
  src/Misc/layoutbin/it-IT/strings.json
  src/Misc/layoutbin/ja-JP/strings.json
  src/Misc/layoutbin/ko-KR/strings.json
  src/Misc/layoutbin/ru-RU/strings.json
  src/Misc/layoutbin/zh-CN/strings.json
  src/Misc/layoutbin/zh-TW/strings.json
Labels: misc

#4456 Users/ismayilov ismayil/add delay when message null
  src/Agent.Listener/MessageListener.cs
Labels: enhancement, Area: Agent

#4466 Restore expanded redaction as a default feature. Add a set of new, highly accurate detections.
  src/Agent.Listener/Configuration/FeatureFlagProvider.cs
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Worker.cs
  src/Microsoft.VisualStudio.Services.Agent/AdditionalMaskingRegexes.CredScan.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Test/L0/HostContextL0.cs
  src/Test/L0/Listener/JobDispatcherL0.cs
Labels: internal

#4467 Users/v kivlev/backport redaction to 3.227.2
  src/Agent.Listener/Configuration/FeatureFlagProvider.cs
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Worker.cs
  src/Microsoft.VisualStudio.Services.Agent/AdditionalMaskingRegexes.CredScan.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Test/L0/HostContextL0.cs
  src/Test/L0/Listener/JobDispatcherL0.cs
  src/agentversion
Labels: internal

#4458 Check task deprecation
  .azure-pipelines/build-job.yml
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/TaskManager.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement

#4460 Enable Domains for Pipeline Artifact
  src/Agent.Plugins/Artifact/PipelineArtifactConstants.cs
  src/Agent.Plugins/Artifact/PipelineArtifactProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactServer.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
Labels: enhancement

#4425 Update process handler
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/Handler.cs
  src/Agent.Worker/Handlers/Helpers/CmdArgsSanitizer.cs
  src/Agent.Worker/Handlers/Helpers/ProcessHandlerHelper.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/Handlers/ProcessHandler.cs
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L0/Worker/Handlers/CmdArgsSanitizerL0.cs
  src/Test/L0/Worker/Handlers/ProcessHandlerHelperL0.cs
  src/Test/L0/Worker/Handlers/ProcessHandlerHelperTelemetryL0.cs
Labels: enhancement

#4423 Add `AllowWorkDirectoryRepositories` knob
  src/Agent.Plugins/RepositoryPlugin.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/BuildDirectoryManager.cs
  src/Agent.Worker/PluginInternalCommandExtension.cs
  src/Test/L0/Plugin/RepositoryPluginL0.cs
  src/Test/L0/Worker/Build/BuildDirectoryManagerL0.cs
  src/Test/L0/Worker/PluginInternalUpdateRepositoryPathCommandL0.cs
Labels: enhancement, Area: Agent

#4478 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20231019085845419 to Localization
  Localize/loc/es-ES/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/fr-FR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ko-KR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ru-RU/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-TW/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement

#4477 Revert "Enable Domains for Pipeline Artifact"
  src/Agent.Plugins/Artifact/PipelineArtifactConstants.cs
  src/Agent.Plugins/Artifact/PipelineArtifactProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactServer.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
Labels: bug

#4474 Add FF for setting git config when out-of-memory problem
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Misc/externals.sh
Labels: internal

#4470 Detect the OS and switch node runner if not supported for Node20
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Misc/externals.sh
Labels: bug

#4483 Mount Workspace
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/ContainerOperationProvider.cs
Labels: bug

#4482 Add capability to publish/download pipeline artifact in a different domain.
  src/Agent.Plugins/Artifact/PipelineArtifactConstants.cs
  src/Agent.Plugins/Artifact/PipelineArtifactProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactServer.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
Labels: bug

#4490 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20231025085014565 to Localization
  Localize/loc/de-DE/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/fr-FR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ja-JP/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ko-KR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ru-RU/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-CN/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement
