Repository microsoft/azure-pipelines-agent, pull requests merged in 2023-07, with the labels that each got.

#4344 Support node 20 handler
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/TaskManager.cs
  src/Misc/externals.sh
  src/Test/L0/NodeHandlerL0.cs
  src/Test/L0/Worker/TaskManagerL0.cs
Labels: enhancement, Area: Build

#4345 Revert "Support node 20 handler"
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/TaskManager.cs
  src/Misc/externals.sh
  src/Test/L0/NodeHandlerL0.cs
  src/Test/L0/Worker/TaskManagerL0.cs
Labels: internal

#4348 Run build stage only from the master branch
  .azure-pipelines/build-job.yml
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
  .vsts.release.yml
Labels: internal

#4346 Support Node 20 handler
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/TaskManager.cs
  src/Misc/externals.sh
  src/Test/L0/NodeHandlerL0.cs
  src/Test/L0/Worker/TaskManagerL0.cs
Labels: enhancement, Area: Build

#4359 Enable end-to-end test in the agent CI
  .vsts.ci.yml
Labels: misc

#4333 Added telemetry classes to produce inline publish functionality
  src/Agent.Listener/Agent.cs
  src/Agent.Listener/Telemetry/CustomerIntelligenceServer.cs
  src/Agent.Listener/Telemetry/TelemetryPublisher.cs
  src/Test/L0/Listener/AgentL0.cs
Labels: enhancement, Area: Agent

#4360 Add `AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL` agent knob
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/Handler.cs
Labels: misc

#4366 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20230720084945943 to Localization
  Localize/loc/de-DE/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/es-ES/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/fr-FR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/it-IT/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ja-JP/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ko-KR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ru-RU/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-CN/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-TW/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement

#4367 WI 2048209
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/ProcessHandler.cs
  src/Agent.Worker/TaskManager.cs
Labels: enhancement

#4350 [Agent] - cert validation changes
  src/Agent.Listener/Agent.cs
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/Configuration/ConfigurationProvider.cs
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.Sdk/CommandPlugin.cs
  src/Agent.Sdk/TaskPlugin.cs
  src/Agent.Sdk/Util/SslUtil.cs
  src/Agent.Sdk/Util/VssUtil.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/Release/Artifacts/BuildArtifact.cs
  src/Agent.Worker/Release/ContainerProvider/FileContainerProvider.cs
  src/Agent.Worker/Release/ContainerProvider/Helpers/ContainerProviderFactory.cs
  src/Agent.Worker/Release/ContainerProvider/Helpers/VssConnectionFactory.cs
  src/Agent.Worker/Variables.cs
  src/Agent.Worker/Worker.cs
  src/Agent.Worker/WorkerUtilties.cs
  src/Microsoft.VisualStudio.Services.Agent/AgentServer.cs
  src/Microsoft.VisualStudio.Services.Agent/Util/ServerUtil.cs
Labels: enhancement

#4371 Move condition result trace from result code to output
  src/Agent.Worker/StepsRunner.cs
Labels: misc

#4372 Add osx-arm64 package to CI pipelines & remove rhel6 from releases
  releaseNote.md
  src/Misc/InstallAgentPackage.template.xml
  src/Misc/Publish.template.ps1
  src/Misc/PublishVSTSAgent.template.ps1
  src/Misc/UnpublishVSTSAgent.template.ps1
Labels: internal
