Repository microsoft/azure-pipelines-agent, pull requests merged in 2023-03, with the labels that each got.

#4161 Added legacy lib sources for support on Ubuntu 22.04
  src/Misc/layoutbin/installdependencies.sh
Labels: misc, dependencies, Area: Agent

#4183 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20230305095015478 to Localization
  Localize/loc/de-DE/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/es-ES/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/fr-FR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/it-IT/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ja-JP/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ko-KR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ru-RU/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-CN/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-TW/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement

#4184 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20230306095225210 to Localization
  Localize/loc/de-DE/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ko-KR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-TW/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement

#4165 Added knob to break pipeline unless user opt-in
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/JobRunner.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement, Area: Agent

#4187 Localization update
  src/Misc/layoutbin/de-DE/strings.json
  src/Misc/layoutbin/es-ES/strings.json
  src/Misc/layoutbin/fr-FR/strings.json
  src/Misc/layoutbin/it-IT/strings.json
  src/Misc/layoutbin/ja-JP/strings.json
  src/Misc/layoutbin/ko-KR/strings.json
  src/Misc/layoutbin/ru-RU/strings.json
  src/Misc/layoutbin/zh-CN/strings.json
  src/Misc/layoutbin/zh-TW/strings.json
Labels: misc

#4200 Add knob to enable fetching net6.json file from GitHub
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/JobRunner.cs
Labels: misc

#4201 Update autoAssignABTT.yml
  .github/workflows/autoAssignABTT.yml
Labels: misc

#4191 Upd dotnet6 agent mar2023
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/workflows/autoAssignABTT.yml
  src/Agent.Listener/net6.json
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/AzureInstanceMetadataProvider.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/StepsRunner.cs
  src/Agent.Worker/TaskRunner.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Misc/layoutbin/de-DE/strings.json
  src/Misc/layoutbin/en-US/strings.json
  src/Misc/layoutbin/es-ES/strings.json
  src/Misc/layoutbin/fr-FR/strings.json
  src/Misc/layoutbin/installdependencies.sh
  src/Misc/layoutbin/it-IT/strings.json
  src/Misc/layoutbin/ja-JP/strings.json
  src/Misc/layoutbin/ko-KR/strings.json
  src/Misc/layoutbin/ru-RU/strings.json
  src/Misc/layoutbin/zh-CN/strings.json
  src/Misc/layoutbin/zh-TW/strings.json
  src/Test/L0/Worker/StepsRunnerL0.cs
Labels: misc

#4195 Added trimmed user secret to masker dictionary
  src/Agent.Worker/Worker.cs
Labels: bug

#4137 [Refactor] Update MinSecretLength property.
  src/Agent.Sdk/Util/ILoggedSecretMasker.cs
  src/Agent.Sdk/Util/LoggedSecretMasker.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L0/SecretMaskerTests/LoggedSecretMaskerL0.cs
Labels: enhancement, Area: Agent

#4209 add ability to disable publishing tests metadata
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/TestResults/Utils/TestResultUtils.cs
Labels: misc
