Repository microsoft/azure-pipelines-agent, pull requests merged in 2023-08, with the labels that each got.

#4390 Fix functional signing L1 tests
  src/Misc/externals.sh
  src/Test/L1/Worker/SigningL1Tests.cs
Labels: misc

#4375 Support Alpine OS
  .azure-pipelines/build-job.yml
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
  assets.json
  images/alpine/Dockerfile
  images/arm/Dockerfile
  images/centos6/Dockerfile
  images/readme.md
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Common.props
  src/Misc/externals.sh
  src/Test/L0/ConstantGenerationL0.cs
  src/Test/L0/NodeHandlerL0.cs
  src/dev.sh
Labels: enhancement

#4347 PlanId fixed in CustomerIntelligence data
  src/Agent.Worker/TaskRunner.cs
Labels: bug, Area: Agent

#4393 fix detect rhel release
  src/dev.sh
Labels: bug

#4394 Update agents git to 2.41.0
  src/Misc/externals.sh
Labels: misc

#4396 fix agent CI - create AzureDevOps PRs
  .gitignore
  .vsts.release.yml
  release/createAdoPrs.js
Labels: misc

#4255 Service Principal auth
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.Listener/CommandLine/ConfigureOrRemoveBase.cs
  src/Agent.Listener/CommandSettings.cs
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/Configuration/CredentialManager.cs
  src/Agent.Listener/Configuration/CredentialProvider.cs
  src/Agent.Listener/Telemetry/TelemetryPublisher.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement

#4401 Download `dotnet-install.(sh/ps1)` script when building the agent
  .gitignore
  src/Misc/dotnet-install.ps1
  src/Misc/dotnet-install.sh
  src/Test/L0/DotnetsdkDownloadScriptL0.cs
  src/dev.sh
Labels: enhancement

#4400 Fix - detect Alpine-based docker image
  src/Agent.Worker/ContainerOperationProvider.cs
Labels: bug

#4404 Enable CI for Alpine (x64)
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
  releaseNote.md
  src/Misc/InstallAgentPackage.template.xml
  src/Misc/Publish.template.ps1
  src/Misc/PublishVSTSAgent.template.ps1
  src/Misc/UnpublishVSTSAgent.template.ps1
Labels: enhancement

#4315 Add Device Code Flow as Pipeline Agent authentication
  src/Agent.Listener/Configuration/CredentialManager.cs
  src/Agent.Listener/Configuration/CredentialProvider.cs
Labels: enhancement, Area: Agent

#4413 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20230831085154349 to Localization
  Localize/loc/ko-KR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ru-RU/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement
