Repository microsoft/azure-pipelines-agent, pull requests merged in 2023-01, with the labels that each got.

#3404 Fix SonarQube's "'Any()' should be used to test for emptiness" / Code…
  src/Agent.Plugins/Artifact/PipelineArtifactServer.cs
  src/Agent.Sdk/ProcessInvoker.Windows.cs
  src/Agent.Worker/Build/TrackingManager.cs
  src/Agent.Worker/CodeCoverage/CodeCoverageCommands.cs
  src/Agent.Worker/Release/ReleaseTrackingManager.cs
  src/Agent.Worker/TaskManager.cs
  src/Test/L0/Listener/CommandSettingsL0.cs
Labels: enhancement

#4092 Add script to predict v2->v3 upgrade compatibility
  tools/FindAgentsNotCompatibleWithAgent/QueryAgentPoolsForCompatibleOS.ps1
  tools/FindAgentsNotCompatibleWithAgent/readme.md
Labels: enhancement

#4103 Added strict boolean knob values
  src/Agent.Sdk/Knob/KnobValue.cs
  src/Agent.Sdk/Util/StringUtil.cs
Labels: enhancement

#4109 [Draft] Set InvariantGlobalization to false for Common.csproj
  src/Common.props
Labels: bug

#4110 update build-job
  .azure-pipelines/build-job.yml
  .azure-pipelines/signing.yml
Labels: internal

#4124 fix dotnet host search
  .azure-pipelines/build-job.yml
Labels: bug

#4121 Add option to skip rhel6 in pipeline and ci
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
  .vsts.release.yml
  release/createAdoPrs.js
  release/fillReleaseNotesTemplate.js
Labels: enhancement

#4112 Update dotnet to 3.1.32
  src/Common.props
  src/dev.sh
Labels: internal

#4100 DockerLogin retries
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Container/DockerCommandManager.cs
  src/Agent.Worker/ContainerOperationProvider.cs
Labels: enhancement

#4104 Add the exact operation system version and environment to the telemetry
  src/Agent.Worker/Build/BuildDirectoryManager.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/TaskRunner.cs
  src/Microsoft.VisualStudio.Services.Agent/ConfigurationStore.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
Labels: enhancement

#4128 Update dotnet6-agent branch from master
  .azure-pipelines/pipeline.yml
  .vsts.release.yml
  src/Agent.Listener/Agent.cs
  src/Agent.Listener/Configuration.Windows/NativeWindowsServiceHelper.cs
  src/Agent.Service/Windows/Program.cs
  src/Agent.Worker/CodeCoverage/CodeCoverageCommands.cs
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Agent.Worker/Handlers/StepHost.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/TaskRunner.cs
  src/Agent.Worker/Variables.cs
  src/Agent.Worker/WorkerCommandManager.cs
  src/Agent.Worker/WorkerUtilties.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/EnvVariableParts.cs
  src/Microsoft.VisualStudio.Services.Agent/Util/VarUtil.cs
  src/Misc/externals.sh
  src/Misc/layoutbin/installdependencies.sh
  src/Misc/layoutroot/config.sh
  src/Misc/layoutroot/env.sh
  src/Test/L0/SecretMaskerTests/LoggedSecretMaskerL0.cs
  src/Test/L0/SecretMaskerTests/SecretMaskerL0.cs
  src/Test/L0/Util/VarUtilL0.cs
  src/Test/L0/Worker/VariablesL0.cs
  src/dev.sh
Labels: internal

#4126 Mingit version upgraded to 2.39.1
  src/Misc/externals.sh
Labels: misc, Area: Agent
