Repository microsoft/azure-pipelines-agent, pull requests merged in 2023-12, with the labels that each got.

#4550 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20231202100120218 to Localization
  Localize/loc/de-DE/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/es-ES/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/it-IT/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-TW/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement

#4552 Localization update
  src/Misc/layoutbin/de-DE/strings.json
  src/Misc/layoutbin/es-ES/strings.json
  src/Misc/layoutbin/fr-FR/strings.json
  src/Misc/layoutbin/it-IT/strings.json
  src/Misc/layoutbin/ja-JP/strings.json
  src/Misc/layoutbin/ko-KR/strings.json
  src/Misc/layoutbin/ru-RU/strings.json
  src/Misc/layoutbin/zh-CN/strings.json
  src/Misc/layoutbin/zh-TW/strings.json
Labels: misc

#4543 Move alpine container to ACR
  .azure-pipelines/pipeline.yml
  images/alpine/Dockerfile
Labels: internal

#4568 Add proper exception handling for Telemetery/FeatureFlag enpoints
  src/Agent.Listener/Configuration/FeatureFlagProvider.cs
  src/Agent.Listener/Telemetry/TelemetryPublisher.cs
Labels: bug

#4575 Added check for existing agent versions in scheduled releases
  .vsts.release.yml
Labels: misc

#4574 Fix release notifications
  .vsts.release.yml
Labels: misc

#4578 Added retry for Install unzip step
  .azure-pipelines/build-job.yml
Labels: misc

#4565 Remove Node 16 Knob from Agent
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
Labels: enhancement, Area: Agent

#4557 Remove the support matrix from the README.md
  README.md
Labels: enhancement, documentation

#4580 Move agent release notifications to separate stage
  .vsts.release.yml
  release/Send-PRsNotification.ps1
Labels: misc
