Repository microsoft/azure-pipelines-agent, pull requests merged in 2023-04, with the labels that each got.

#4213 Refactor logic to drain queues after each task
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/StepsRunner.cs
  src/Microsoft.VisualStudio.Services.Agent/JobServerQueue.cs
Labels: bug

#4218 Upgrade git-lfs version
  src/Misc/externals.sh
Labels: misc

#4202 Add noderunner.md
  docs/noderunner.md
Labels: documentation, misc

#4243 Dotnet6 agent merge master
  docs/noderunner.md
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/ILoggedSecretMasker.cs
  src/Agent.Sdk/Util/LoggedSecretMasker.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/JobExtension.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/StepsRunner.cs
  src/Agent.Worker/TaskCommandExtension.cs
  src/Agent.Worker/TestResults/Utils/TestResultUtils.cs
  src/Agent.Worker/Worker.cs
  src/Agent.Worker/WorkerCommandManager.cs
  src/Microsoft.VisualStudio.Services.Agent/JobServerQueue.cs
  src/Misc/externals.sh
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L0/SecretMaskerTests/LoggedSecretMaskerL0.cs
  src/Test/L0/Worker/TaskCommandExtensionL0.cs
  src/agentversion
Labels: internal

#3831 Fix: Remove invalid chars from filename
  src/Agent.Worker/ExecutionContext.cs
Labels: bug

#4236 Add force of _tasks creation by knob
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/JobExtension.cs
Labels: misc

#4252 Upd dotnet6 agent before merge with master
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.PluginHost/Agent.PluginHost.csproj
  src/Agent.Plugins/Agent.Plugins.csproj
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/Agent.Worker.csproj
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/JobExtension.cs
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobFileInfo.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobStoreUtils.cs
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
  src/Test/L1/Mock/FakeJobServer.cs
  src/Test/Test.csproj
  src/agentversion
Labels: internal

#4254 Update master with dotnet 6
  .azure-pipelines/build-job.yml
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
  releaseNote.md
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.Listener/Configuration.Windows/WindowsServiceControlManager.cs
  src/Agent.Listener/NuGet.Config
  src/Agent.Listener/SelfUpdater.cs
  src/Agent.Plugins/TFCliManager.cs
  src/Agent.Plugins/TeeCliManager.cs
  src/Agent.Plugins/TfsVCCliManager.cs
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/AzureInstanceMetadataProvider.cs
  src/Agent.Worker/Build/TFCommandManager.cs
  src/Agent.Worker/Build/TeeCommandManager.cs
  src/Agent.Worker/Build/TfsVCCommandManager.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/Handlers/StepHost.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/Variables.cs
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
  src/Microsoft.VisualStudio.Services.Agent/Util/VarUtil.cs
  src/Misc/dotnet-install.sh
  src/Misc/externals.sh
  src/Misc/layoutbin/installdependencies.sh
  src/Misc/layoutroot/config.sh
  src/Misc/layoutroot/env.sh
  src/Test/L0/ConstantGenerationL0.cs
  src/Test/L0/HostContextExtensionL0.cs
  src/Test/L0/Listener/AgentL0.cs
  src/Test/L0/Listener/Configuration/AgentCapabilitiesProviderTestL0.cs
  src/Test/L0/Listener/JobDispatcherL0.cs
  src/Test/L0/Plugin/ChunkerTests.cs
  src/Test/L0/Plugin/FingerprintCreatorTests.cs
  src/Test/L0/Plugin/LogPluginHostL0.cs
  src/Test/L0/Plugin/TestFileShareProvider/TestFileShareProviderL0.cs
  src/Test/L0/Plugin/TestResultParser/EnumerableExtensionL0.cs
  src/Test/L0/ProcessExtensionL0.cs
  src/Test/L0/TestHostContext.cs
  src/Test/L0/Util/IOUtilL0.cs
  src/Test/L1/Mock/FakeConfigurationStore.cs
  src/agentversion
  src/dev.sh
  tools/CredScanRegexes/readme.md
Labels: internal

#4238 update node from `16.17.1` to `16.20.0`
  src/Misc/externals.sh
Labels: misc
