Repository microsoft/azure-pipelines-agent, pull requests merged in 2023-06, with the labels that each got.

#4312 Cherry-picked: Add disableInlineExecution
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/ProcessHandler.cs
  src/Agent.Worker/TaskManager.cs
Labels: enhancement

#4157 Adding support to Pipeline Artifact and Pipeline Caching, for larger chunk size.
  src/Agent.Plugins/Artifact/ArtifactProviderFactory.cs
  src/Agent.Plugins/Artifact/FileContainerProvider.cs
  src/Agent.Plugins/Artifact/FileShareProvider.cs
  src/Agent.Plugins/Artifact/IArtifactProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactConstants.cs
  src/Agent.Plugins/Artifact/PipelineArtifactProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactServer.cs
  src/Agent.Plugins/PipelineArtifact/FilePathServer.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
Labels: enhancement, Area: Agent

#4326 Update dotnet install scripts
  src/Misc/dotnet-install.sh
Labels: internal

#4335 Test Proxy Agent
  .azure-pipelines/pipeline.yml
  .azure-pipelines/scripts/run-and-verify.js
  .vsts.release.yml
Labels: internal
