Repository microsoft/azure-pipelines-agent, pull requests merged in 2023-05, with the labels that each got.

#4260 Fix that plugins ignores proxy configuration
  src/Agent.Sdk/AgentWebProxy.cs
  src/Agent.Sdk/CommandPlugin.cs
  src/Agent.Sdk/LogPlugin.cs
  src/Agent.Sdk/TaskPlugin.cs
  src/Test/L0/Plugin/LogPluginHostL0.cs
  src/Test/L0/Plugin/RepositoryPluginL0.cs
Labels: bug

#4249 Fix httpclient timeout on AzureMetada retrieving
  src/Agent.Sdk/Util/AzureInstanceMetadataProvider.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/StepsRunner.cs
  src/Test/L0/Worker/JobRunnerL0.cs
Labels: bug

#4264 Update link to new NodeTaskRunnerInstaller@0 article in task reference
  docs/noderunner.md
Labels: misc

#4259 Pass Process handler args through env variables
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/Handler.cs
  src/Agent.Worker/Handlers/Helpers/ProcessHandlerHelper.cs
  src/Agent.Worker/Handlers/ProcessHandler.cs
  src/Test/L0/Worker/Handlers/ProcessHandlerHelperL0.cs
  src/Test/L0/Worker/Handlers/ProcessHandlerHelperTelemetryL0.cs
Labels: enhancement

#4269 Bump default agent version to 3.999.999
  src/agentversion
Labels: misc

#4277 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20230516085151802 to Localization
  Localize/loc/fr-FR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ja-JP/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ru-RU/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement

#4278 Revert PR 4220 "Upgrade vss api netcore version, has BuildXL changes"
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.PluginHost/Agent.PluginHost.csproj
  src/Agent.Plugins/Agent.Plugins.csproj
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/Agent.Worker.csproj
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobFileInfo.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobStoreUtils.cs
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
  src/Test/L1/Mock/FakeJobServer.cs
  src/Test/Test.csproj
Labels: bug

#4279 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20230517085117344 to Localization
  Localize/loc/de-DE/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/es-ES/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/it-IT/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ko-KR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-CN/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-TW/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement

#4282 Fix PH telemetry debug formatting
  src/Agent.Worker/Handlers/ProcessHandler.cs
Labels: bug

#4285 Cherry pick changes to 3.220.3 process handler args
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/Handler.cs
  src/Agent.Worker/Handlers/Helpers/ProcessHandlerHelper.cs
  src/Agent.Worker/Handlers/ProcessHandler.cs
  src/Test/L0/Worker/Handlers/ProcessHandlerHelperL0.cs
  src/Test/L0/Worker/Handlers/ProcessHandlerHelperTelemetryL0.cs
Labels: internal

#4286 Reverse defult value of the AGENT_PH_ENABLE_SECURE_ARGUMENTS & AGENT_PH_ENABLE_TELEMETRY
  src/Agent.Sdk/Knob/AgentKnobs.cs
Labels: internal

#4287 Fix PH `modifyEnvironment`
  src/Agent.Worker/Handlers/ProcessHandler.cs
Labels: bug

#4292 Upgrade vss-api-netcore package
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.PluginHost/Agent.PluginHost.csproj
  src/Agent.Plugins/Agent.Plugins.csproj
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Worker/Agent.Worker.csproj
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobFileInfo.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobStoreUtils.cs
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
  src/Test/L1/Mock/FakeJobServer.cs
  src/Test/Test.csproj
Labels: enhancement

#4294 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20230525085047495 to Localization
  Localize/loc/ru-RU/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement

#4152 Allow the agent running in PowerShell to use the PowerShell handler
  src/Agent.Sdk/Util/ProcessUtil.cs
  src/Agent.Worker/Handlers/Handler.cs
  src/Agent.Worker/Handlers/PowerShell3Handler.cs
  src/Agent.Worker/Handlers/PowerShellExeHandler.cs
  src/Test/L0/Util/ProcessUtilL0.cs
Labels: bug
