Repository microsoft/azure-pipelines-agent, pull requests merged in 2023-02, with the labels that each got.

#4117 Fix agent lint errors
  src/Agent.Listener/Configuration.Windows/NativeWindowsServiceHelper.cs
  src/Agent.Sdk/Util/ExceptionsUtil.cs
  src/Agent.Sdk/Util/ILoggedSecretMasker.cs
  src/Agent.Sdk/Util/LoggedSecretMasker.cs
  src/Agent.Sdk/Util/MaskingUtil.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Service/Windows/Program.cs
  src/Agent.Worker/CodeCoverage/CodeCoverageCommands.cs
  src/Agent.Worker/Handlers/StepHost.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/WorkerCommandManager.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Test/L0/SecretMaskerTests/LoggedSecretMaskerL0.cs
  src/Test/L0/SecretMaskerTests/SecretMaskerL0.cs
Labels: misc

#4143 Revert "Allow env.sh to accept additional env var names (#3339)"
  src/Misc/layoutroot/env.sh
Labels: misc

#4144 Revert "Allow env.sh to accept additional env var names"
  src/Misc/layoutroot/env.sh
Labels: bug

#4150 Upd dotnet6 agent
  .vsts.ci.yml
  src/Agent.Sdk/Util/ExceptionsUtil.cs
  src/Agent.Sdk/Util/ILoggedSecretMasker.cs
  src/Agent.Sdk/Util/LoggedSecretMasker.cs
  src/Agent.Sdk/Util/MaskingUtil.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Agent.Worker/Handlers/StepHost.cs
  src/Agent.Worker/WorkerCommandManager.cs
  src/Misc/externals.sh
  src/Test/L0/SecretMaskerTests/LoggedSecretMaskerL0.cs
Labels: internal

#4151 Update minor .net6 version
  .azure-pipelines/build-job.yml
  .vsts.ci.yml
  src/Common.props
  src/dev.sh
Labels: internal

#4136 Feature:2024632 - Fail RHEL 6 on v2 agent, unless a knob is set
  .azure-pipelines/build-job.yml
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/JobRunner.cs
  src/Test/L0/Worker/JobRunnerL0.cs
  src/Test/L1/Worker/L1TestBase.cs
Labels: misc

#4155 Bump azure pipelines task lib to 4.2.0
  release/package-lock.json
  release/package.json
Labels: internal

#4156 Bump azure pipelines task lib to 4.2.0
  release/package-lock.json
  release/package.json
Labels: internal

#4168 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20230223095051399 to Localization
  Localize/loc/es-ES/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/fr-FR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/it-IT/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ko-KR/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ru-RU/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-TW/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement

#4162 Add warning for deprecated runners
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: misc

#4166 FEATURE 2019014 - Gather telemetry on Agent Azure & Docker Container usage
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Sdk/Util/AzureInstanceMetadataProvider.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/TaskRunner.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
Labels: enhancement

#4170 LEGO: Pull request from lego/hb_5733438c-38c5-41ae-9557-a9d9754c4535_20230224095040576 to Localization
  Localize/loc/de-DE/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/ja-JP/src/Misc/layoutbin/en-US/strings.json.lcl
  Localize/loc/zh-CN/src/Misc/layoutbin/en-US/strings.json.lcl
Labels: enhancement
