Repository microsoft/azure-pipelines-agent, pull requests merged in 2024-06, with the labels that each got.

#4794 Check if task node runner is deprecated
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/TaskManager.cs
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L0/TestHostContext.cs
Labels: enhancement

#4822 Explain error when downloading Node Alpine ARM64
  .vsts.ci.yml
  src/Misc/externals.sh
Labels: enhancement

#4807 Revert "Skip checkout for Set_variables Release job"
  .vsts.release.yml
Labels: internal

#3479 Added option to use a checkout path of any repository as the default working directory (System.DefaultWorkingDirectory)
  src/Agent.Sdk/TaskPlugin.cs
  src/Agent.Sdk/Util/RepositoryUtil.cs
  src/Agent.Worker/Build/BuildJobExtension.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/PluginInternalCommandExtension.cs
  src/Test/L0/Worker/Build/BuildJobExtensionL0.cs
  src/Test/L0/Worker/ExecutionContextL0.cs
Labels: enhancement

#4778 Display warning when the agent is run in PowerShell Core
  src/Agent.Listener/Agent.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/ProcessUtil.cs
  src/Agent.Sdk/Util/PsModulePathUtil.cs
  src/Agent.Sdk/Util/WindowsProcessUtil.cs
  src/Agent.Worker/Handlers/Handler.cs
  src/Agent.Worker/Handlers/PowerShell3Handler.cs
  src/Agent.Worker/Handlers/PowerShellExeHandler.cs
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L0/Util/ProcessUtilL0.cs
Labels: bug

#4827 Update MinGit to v2.45.2
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/GitCommandManager.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Misc/externals.sh
  src/Test/L0/Plugin/TestGitCliManager/TestGitCliManagerL0.cs
  src/Test/L0/Worker/Build/GitCommandManagerL0.cs
Labels: internal

#4836 Refactor inputs parsing in task runner & fix publishing telemetry from node handler
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/TaskRunner.cs
Labels: internal

#4843 Update git-lfs to v3.4.0
  src/Misc/externals.sh
Labels: internal

#4839 Bump System.Security.Cryptography.Pkcs to 7.0.2 and Microsoft.Azure.Storage.DataMovement 2.0.5
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.PluginHost/Agent.PluginHost.csproj
  src/Agent.Plugins/Agent.Plugins.csproj
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Worker/Agent.Worker.csproj
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
  src/Test/Test.csproj
Labels: bug

#4803 Rework resource monitor
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/ResourceMetricsManager.cs
  src/Agent.Worker/TaskRunner.cs
  src/Test/L1/Mock/FakeResourceMetricsManager.cs
Labels: enhancement, Area: Agent

#4852 Update docs to include information about debugging
  docs/contribute.md
Labels: documentation

#4858 Remove PAT from the agent CI
  .azure-pipelines/get-pat.yml
  .azure-pipelines/pipeline.yml
Labels: misc

#4851 Use useradd on Alpine when user ID is large
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: bug

#4864 Remove ADO PAT for PRs
  .azure-pipelines/pipeline.yml
  .vsts.release.yml
Labels: misc

#4850 Add mechanism to download Git on Initialize step
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/GitManager.cs
  src/Agent.Worker/JobExtension.cs
  src/Test/L0/Plugin/TestGitCliManager/TestGitCliManagerL0.cs
  src/Test/L0/Worker/GitManagerL0.cs
Labels: internal

#4868 Mask ACR token on Windows when System.Debug is true
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Container/DockerCommandManager.cs
  src/Agent.Worker/ContainerOperationProvider.cs
Labels: bug

#4877 Localization update
  src/Misc/layoutbin/de-DE/strings.json
  src/Misc/layoutbin/es-ES/strings.json
  src/Misc/layoutbin/fr-FR/strings.json
  src/Misc/layoutbin/it-IT/strings.json
  src/Misc/layoutbin/ja-JP/strings.json
  src/Misc/layoutbin/ko-KR/strings.json
  src/Misc/layoutbin/ru-RU/strings.json
  src/Misc/layoutbin/zh-CN/strings.json
  src/Misc/layoutbin/zh-TW/strings.json
Labels: misc
