Repository microsoft/azure-pipelines-agent, pull requests merged in 2024-01, with the labels that each got.

#4585 Add the tailored deprecation message in addition to the common deprecation message
  src/Agent.Worker/TaskManager.cs
Labels: enhancement

#4595 Bump dotnet to 6.0.26
  .azure-pipelines/build-job.yml
  src/Common.props
  src/dev.sh
Labels: internal

#4598 Add core.longpaths to git provider
  src/Agent.Plugins/GitSourceProvider.cs
Labels: bug

#4134 Fix step unit test failures in agent pipeline
  src/Test/L0/ProcessInvokerL0.cs
Labels: internal

#4604 Mock FF Git version in TestGitCliManagerL0 unit test
  src/Test/L0/Plugin/TestGitCliManager/TestGitCliManagerL0.cs
Labels: internal

#4559 Add resource utilization warnings
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/ResourceMetricsManager.cs
  src/Agent.Worker/TaskRunner.cs
  src/Misc/layoutbin/en-US/strings.json
  src/Test/L1/Mock/FakeResourceMetricsManager.cs
Labels: enhancement, Area: Agent

#4473 Remove Node 6 Runner from installation step
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/JobExtension.cs
  src/Agent.Worker/NodeJsUtil.cs
  src/Agent.Worker/TaskManager.cs
Labels: enhancement, Area: Agent

#4607 Implemented option to store token in named container
  src/Agent.Listener/Configuration.Windows/RSAEncryptedFileKeyManager.cs
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/Configuration/FeatureFlagProvider.cs
  src/Agent.Listener/Configuration/IRSAKeyManager.cs
  src/Agent.Listener/Configuration/OAuthCredential.cs
  src/Agent.Listener/Configuration/RSAFileKeyManager.cs
  src/Agent.Listener/MessageListener.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Test/L0/Listener/Configuration/ConfigurationManagerL0.cs
  src/Test/L0/Listener/MessageListenerL0.cs
Labels: enhancement

#4610 Update github workflows to avoid issues with GITHUB_TOKEN
  .github/workflows/autoAssignABTT.yml
  .github/workflows/localization-automerge.yml
  .github/workflows/stale.yml
Labels: internal

#4605 Pipeline agent unable to kill the last task in time
  src/Agent.Worker/StepsRunner.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement

#4617 Add multiple domain support to Build Artifacts upload/download
  src/Agent.Plugins/Artifact/FileContainerProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactServer.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/FileContainerServer.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobStoreUtils.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobstoreClientSettings.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
  src/Microsoft.VisualStudio.Services.Agent/JobServer.cs
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
Labels: enhancement

#4615 Add possibility to get info from /usr/lib/os-release file.
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/TaskRunner.cs
  src/Misc/layoutbin/installdependencies.sh
Labels: bug

#4597 Add pipeline feature knob source
  src/Agent.Sdk/Knob/PipelineFeatureSource.cs
  src/Agent.Sdk/Knob/RuntimeKnobSource.cs
  src/Test/L0/KnobL0.cs
Labels: enhancement

#4623 Mock git ff (#4604)
  src/Test/L0/Plugin/TestGitCliManager/TestGitCliManagerL0.cs
Labels: internal
