Repository microsoft/azure-pipelines-agent, pull requests merged in 2024-03, with the labels that each got.

#4693 Handle filter option for treeless or blobless git fetches
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Common.props
  src/Test/L0/Plugin/RepositoryPluginL0.cs
Labels: enhancement

#4695 Implemented option to store token in named container
  docs/design/auth.md
  src/Agent.Listener/Configuration.Windows/RSAEncryptedFileKeyManager.cs
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/Configuration/FeatureFlagProvider.cs
  src/Agent.Listener/Configuration/IRSAKeyManager.cs
  src/Agent.Listener/Configuration/RSAFileKeyManager.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Test/L0/Listener/Configuration/ConfigurationManagerL0.cs
  src/Test/L0/Listener/MessageListenerL0.cs
Labels: internal

#4705 Changes for Azure Test Plan Task
  src/Agent.Worker/TestResults/ResultsCommandExtension.cs
  src/Agent.Worker/TestResults/TestDataPublisher.cs
  src/Agent.Worker/TestResults/Utils/TestResultsConstants.cs
  src/Common.props
Labels: enhancement, Area: Test

#4700 Remove old ruleset
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.PluginHost/Agent.PluginHost.csproj
  src/Agent.Plugins/Agent.Plugins.csproj
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Service/Windows/AgentService.csproj
  src/Agent.Worker/Agent.Worker.csproj
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
  src/rules.ruleset
Labels: internal

#4701 Update .editorconfig rules
  .editorconfig
Labels: internal

#4708 Follow up PR for Azure Test Plan Changes in Result.Publish
  src/Agent.Worker/TestResults/ResultsCommandExtension.cs
Labels: Area: Test, misc

#4706 Skip checkout for Set_variables Release job
  .vsts.release.yml
Labels: internal

#4714 [BUG]: Installing DevOpsAgent on SLES 15 fails
  src/Misc/layoutbin/installdependencies.sh
Labels: bug

#4662 Add validation for the task.issue command
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/TaskPlugin.cs
  src/Agent.Worker/Build/TfsVCCommandManager.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/TaskCommandExtension.cs
  src/Agent.Worker/TaskManager.cs
  src/Agent.Worker/TaskRunner.cs
  src/Agent.Worker/WorkerUtilties.cs
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Test/L0/Worker/TaskCommandExtensionL0.cs
Labels: enhancement, Area: Agent

#4690 Set terminal output/input encodings to utf-8
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Microsoft.VisualStudio.Services.Agent/Terminal.cs
Labels: internal

#4737 Remove Node 10 runner from pipelines-* Agent packages
  .azure-pipelines/build-jobs.yml
  src/Misc/externals.sh
  src/dev.sh
Labels: internal, Area: Agent
