Repository microsoft/azure-pipelines-agent, pull requests merged in 2024-02, with the labels that each got.

#4630 Change CI timeout to the default value (10 minutes)
  .azure-pipelines/pipeline.yml
Labels: misc

#4631 Revert "Implemented option to store token in named container"
  src/Agent.Listener/Configuration.Windows/RSAEncryptedFileKeyManager.cs
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/Configuration/FeatureFlagProvider.cs
  src/Agent.Listener/Configuration/IRSAKeyManager.cs
  src/Agent.Listener/Configuration/OAuthCredential.cs
  src/Agent.Listener/Configuration/RSAFileKeyManager.cs
  src/Agent.Listener/MessageListener.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Test/L0/Listener/Configuration/ConfigurationManagerL0.cs
  src/Test/L0/Listener/MessageListenerL0.cs
Labels: bug, Area: Agent

#4620 Support variables where case is preserved
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Worker/Build/GitCommandManager.cs
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/Handlers/Handler.cs
  src/Agent.Worker/Handlers/LegacyPowerShellHandler.cs
  src/Agent.Worker/Handlers/PowerShellExeHandler.cs
  src/Agent.Worker/Handlers/ProcessHandler.cs
  src/Agent.Worker/Release/AgentUtilities.cs
  src/Agent.Worker/TaskCommandExtension.cs
  src/Agent.Worker/TaskRunner.cs
  src/Agent.Worker/Variables.cs
  src/Microsoft.VisualStudio.Services.Agent/Util/VarUtil.cs
  src/Test/L0/Util/VarUtilL0.cs
  src/Test/L0/Worker/Build/BuildJobExtensionL0.cs
  src/Test/L0/Worker/PluginInternalUpdateRepositoryPathCommandL0.cs
  src/Test/L0/Worker/Release/AgentUtlitiesL0.cs
  src/Test/L0/Worker/Release/ReleaseJobExtensionL0.cs
  src/Test/L0/Worker/SetVariableRestrictionsL0.cs
  src/Test/L0/Worker/VariablesL0.cs
Labels: enhancement

#4635 Fix agent release 'build stage only' option
  .azure-pipelines/build-job.yml
  .azure-pipelines/scripts/Switch-Branch.ps1
  .azure-pipelines/switch-branch.yml
  .vsts.release.yml
Labels: internal

#4636 Fix switch to target branch CI step
  .azure-pipelines/build-job.yml
  .azure-pipelines/scripts/Switch-Branch.ps1
  .azure-pipelines/scripts/switch-branch.sh
  .vsts.release.yml
Labels: misc

#4616 Pipeline repository name
  src/Agent.Worker/Build/BuildJobExtension.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
Labels: misc

#4609 Use workFolder root as target for disk space monitoring
  src/Agent.Worker/ResourceMetricsManager.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement, Area: Agent

#4638 Use PowerShell instead of bash for the release stage
  .azure-pipelines/scripts/switch-branch.ps1
  .vsts.release.yml
Labels: bug

#4640 Change pool for Create PRs stage
  .vsts.release.yml
Labels: misc

#4622 Clean up warnings in agent
  src/Agent.Listener/CommandSettings.cs
  src/Agent.Listener/Configuration.Linux/SystemdControlManager.cs
  src/Agent.Listener/Configuration.Windows/AutoLogonManager.cs
  src/Agent.Listener/Configuration.Windows/AutoLogonRegistryManager.cs
  src/Agent.Listener/Configuration.Windows/NativeWindowsServiceHelper.cs
  src/Agent.Listener/Configuration.Windows/RSAEncryptedFileKeyManager.cs
  src/Agent.Listener/Configuration.Windows/WindowsRegistryManager.cs
  src/Agent.Listener/Configuration.Windows/WindowsServiceControlManager.cs
  src/Agent.Listener/Configuration.macOS/MacOSServiceControlManager.cs
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/Configuration/CredentialProvider.cs
  src/Agent.Listener/Configuration/Validators.cs
  src/Agent.Plugins/PipelineCache/FingerprintCreator.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
  src/Agent.Sdk/Util/NetFrameworkUtil.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Sdk/Util/TeeUtil.cs
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Agent.Worker/DiagnosticLogManager.cs
  src/Agent.Worker/Handlers/HandlerFactory.cs
  src/Agent.Worker/Handlers/PowerShell3Handler.cs
  src/Agent.Worker/Handlers/PowerShellExeHandler.cs
  src/Agent.Worker/ManagementScriptStep.cs
  src/Agent.Worker/Release/Artifacts/CustomArtifact.cs
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/AgentCredentialStore/WindowsAgentCredentialStore.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobStoreUtils.cs
  src/Microsoft.VisualStudio.Services.Agent/Capabilities/AgentCapabilitiesProvider.cs
  src/Microsoft.VisualStudio.Services.Agent/Capabilities/NixCapabilitiesProvider.cs
  src/Microsoft.VisualStudio.Services.Agent/Capabilities/PowerShellCapabilitiesProvider.cs
  src/Microsoft.VisualStudio.Services.Agent/Util/PowerShellExeUtil.cs
  src/Test/L0/Listener/Configuration/ServiceControlManagerL0.cs
  src/Test/L0/Plugin/FingerprintCreatorTests.cs
  src/Test/L1/Mock/FakeResourceMetricsManager.cs
  src/Test/Test.csproj
  src/dir.proj
Labels: internal

#4652 Updated Moq to 4.20.70
  src/Test/Test.csproj
Labels: internal

#4628 Record task name logging in user agent
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/VssUtil.cs
  src/Agent.Worker/TaskRunner.cs
Labels: misc

#4666 [AgentWorker.PageLogger] - Ignore endgroup tag when counting lines
  src/Microsoft.VisualStudio.Services.Agent/Logging.cs
  src/Test/L0/PagingLoggerL0.cs
Labels: bug

#4649 Fixed unit test file names in the TestLogs directory
  src/Test/L0/TestHostContext.cs
Labels: internal

#4618 Update Git to v2.43.0
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/GitCommandManager.cs
  src/Agent.Worker/Build/GitSourceProvider.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Misc/externals.sh
  src/Test/L0/Plugin/TestGitCliManager/TestGitCliManagerL0.cs
  src/Test/L0/Plugin/TestGitSourceProvider/GitSourceProviderL0.cs
  src/Test/L0/Plugin/TestGitSourceProvider/MockAgentTaskPluginExecutionContext.cs
  src/Test/L0/Worker/Build/GitCommandManagerL0.cs
  src/Test/L0/Worker/Build/GitSourceProviderL0.cs
Labels: internal

#4629 Added .editorconfig
  .editorconfig
  src/Common.props
Labels: internal

#4644 [WI 2129366] Decrease WARNING_MESSAGE_INTERVAL
  src/Agent.Worker/ResourceMetricsManager.cs
Labels: enhancement, Area: Agent

#4676 Increasing PTR Timeout for Legacy Workflow
  src/Agent.Worker/TestResults/Legacy/TestRunPublisher.cs
Labels: bug

#4660 Change Agent release pipeline pool
  .vsts.release.yml
Labels: misc, Area: Agent

#4671 Localization update
  src/Misc/layoutbin/de-DE/strings.json
  src/Misc/layoutbin/es-ES/strings.json
  src/Misc/layoutbin/fr-FR/strings.json
  src/Misc/layoutbin/it-IT/strings.json
  src/Misc/layoutbin/ja-JP/strings.json
  src/Misc/layoutbin/ko-KR/strings.json
  src/Misc/layoutbin/ru-RU/strings.json
  src/Misc/layoutbin/zh-CN/strings.json
  src/Misc/layoutbin/zh-TW/strings.json
Labels: misc

#4680 Bumping vulnerable packages
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
Labels: misc, Area: Agent

#4664 Add keepalive request
  src/Agent.Listener/Agent.cs
  src/Agent.Listener/MessageListener.cs
Labels: enhancement, Area: ABTT

#4678 Update to m235 ADO clients
  src/Common.props
Labels: bug

#4670 1ES Pipelines Template Adoption
  .azure-pipelines/build-job.yml
  .azure-pipelines/build-jobs.yml
  .azure-pipelines/package-vcredist.yml
  .azure-pipelines/pipeline.yml
  .azure-pipelines/signing.yml
  .gdn/.gdnbaselines
  .vsts.ci.yml
  .vsts.release.yml
  release/util.js
Labels: internal

#4679 Adding auth for nuget operations
  .azure-pipelines/build-job.yml
Labels: internal

#4684 Fix bug where chunking could use different hash than the client
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobStoreUtils.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
Labels: bug
