Repository microsoft/azure-pipelines-agent, pull requests merged in 2024-08, with the labels that each got.

#4885 Show warnings for Agents that run on OS versions not supported by .NET 8
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.Listener/SelfUpdater.cs
  src/Agent.Listener/net8.json
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/JobExtension.cs
  src/Misc/layoutbin/de-DE/strings.json
  src/Misc/layoutbin/en-US/strings.json
  src/Misc/layoutbin/es-ES/strings.json
  src/Misc/layoutbin/fr-FR/strings.json
  src/Misc/layoutbin/it-IT/strings.json
  src/Misc/layoutbin/ja-JP/strings.json
  src/Misc/layoutbin/ko-KR/strings.json
  src/Misc/layoutbin/ru-RU/strings.json
  src/Misc/layoutbin/zh-CN/strings.json
  src/Misc/layoutbin/zh-TW/strings.json
Labels: enhancement, Area: ABTT, Area: Agent

#4912 Update dotnet sdk to v6.0.424/runtime to v6.0.32
  .azure-pipelines/build-job.yml
  src/Common.props
  src/dev.sh
Labels: misc, dependencies

#4924 Add PipelineFeatureSource CheckIfTaskNodeRunnerIsDeprecated
  src/Agent.Sdk/Knob/AgentKnobs.cs
Labels: misc

#4926 Bring back debugging capabilities on the agent
  src/Agent.Listener/Agent.cs
  src/Agent.Listener/CommandLine/RunAgent.cs
  src/Agent.Listener/CommandSettings.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Microsoft.VisualStudio.Services.Agent/ConfigurationStore.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
Labels: enhancement

#4909 Localization update
  src/Misc/layoutbin/de-DE/strings.json
  src/Misc/layoutbin/es-ES/strings.json
  src/Misc/layoutbin/fr-FR/strings.json
  src/Misc/layoutbin/it-IT/strings.json
  src/Misc/layoutbin/ja-JP/strings.json
  src/Misc/layoutbin/ko-KR/strings.json
  src/Misc/layoutbin/ru-RU/strings.json
  src/Misc/layoutbin/zh-CN/strings.json
  src/Misc/layoutbin/zh-TW/strings.json
Labels: misc

#4930 Add package type info to telemetry messages
  src/Agent.Worker/TaskRunner.cs
Labels: enhancement, Area: Agent

#4928 Add handling of timeout exceptions for FF provider
  src/Agent.Listener/Configuration/FeatureFlagProvider.cs
Labels: bug, Area: Agent

#4929 Use `node20_1` for `sleepCommand` when running container
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
Labels: misc

#4888 Improve CPU resource monitor for Linux systems
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/ResourceMetricsManager.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: enhancement

#4940 Fix inputs trimming for variables
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/TaskRunner.cs
  src/Agent.Worker/Variables.cs
  src/Microsoft.VisualStudio.Services.Agent/Util/VarUtil.cs
Labels: bug

#4946 Add Red Hat based distros to supported list
  src/Agent.Listener/net8.json
  src/Agent.Worker/JobExtension.cs
Labels: enhancement, Area: Agent
