Repository microsoft/azure-pipelines-agent, pull requests merged in 2024-07, with the labels that each got.

#4878 Rename AZP_USENEWNODEHANDLERTELEMETRY knob
  src/Agent.Sdk/Knob/AgentKnobs.cs
Labels: internal

#4881 Use feature flag knob source for Process Handler V2
  src/Agent.Sdk/Knob/AgentKnobs.cs
Labels: internal

#4891 Mask Service Principal credential in agent logs
  src/Agent.Listener/CommandSettings.cs
  src/Agent.Sdk/Util/WellKnownSecretAliases.cs
Labels: bug

#4893 Add image version telemetry
  src/Agent.Worker/JobExtension.cs
Labels: misc

#4756 Added ShellTasksValidation audit action data to issues
  src/Agent.Worker/Handlers/ProcessHandler/ProcessHandlerHelper.cs
  src/Agent.Worker/Handlers/ProcessHandler/ProcessHandlerV2.cs
Labels: internal

#4898 Revert "Allow running agent in debugging mode for specific node task"
  src/Agent.Listener/Agent.cs
  src/Agent.Listener/CommandLine/RunAgent.cs
  src/Agent.Listener/CommandSettings.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Microsoft.VisualStudio.Services.Agent/ConfigurationStore.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
Labels: internal

#4905 Update the pipelines agent dependency System.Formats.Asn1
  src/Agent.Listener/Agent.Listener.csproj
  src/Agent.PluginHost/Agent.PluginHost.csproj
  src/Agent.Plugins/Agent.Plugins.csproj
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Worker/Agent.Worker.csproj
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
  src/Test/Test.csproj
Labels: internal, dependencies

#4906 Remove `AZP_AGENT_MOUNT_WORKSPACE` knob
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: misc

#4894 Test branch cleanup for release pipeline
  .vsts.release.yml
  release/createAdoPrs.js
Labels: Area: Test, misc

#4915 Perform Node 6-16 -> 20 runner upgrade experiment
  src/Agent.Worker/ExecutionContext.cs
  src/Agent.Worker/Telemetry/TelemetryCommandExtension.cs
Labels: internal
