Repository microsoft/azure-pipelines-agent, pull requests merged in 2024-04, with the labels that each got.

#4735 Agent's git should not use HTTP/2.0 (use HTTP/1.1 instead)
  src/Agent.Worker/Build/GitSourceProvider.cs
Labels: internal

#4743 Add exclusion for telemetry whitelist for MS Extensions
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
Labels: internal

#4719 Bump default node version for runsvc
  src/Misc/layoutbin/runsvc.sh
Labels: enhancement

#4740 Localization update
  src/Misc/layoutbin/de-DE/strings.json
  src/Misc/layoutbin/es-ES/strings.json
  src/Misc/layoutbin/fr-FR/strings.json
  src/Misc/layoutbin/it-IT/strings.json
  src/Misc/layoutbin/ja-JP/strings.json
  src/Misc/layoutbin/ko-KR/strings.json
  src/Misc/layoutbin/ru-RU/strings.json
  src/Misc/layoutbin/zh-CN/strings.json
  src/Misc/layoutbin/zh-TW/strings.json
Labels: misc

#4723 Replace WMI query with interop
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/ProcessUtil.cs
  src/Agent.Worker/Handlers/Handler.cs
  src/Test/L0/Util/ProcessUtilL0.cs
Labels: bug

#4711 Refactor ProcessHandler arguments logic
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Handlers/HandlerFactory.cs
  src/Agent.Worker/Handlers/ProcessHandler/CmdArgsSanitizer.cs
  src/Agent.Worker/Handlers/ProcessHandler/Exceptions.cs
  src/Agent.Worker/Handlers/ProcessHandler/ProcessHandler.cs
  src/Agent.Worker/Handlers/ProcessHandler/ProcessHandlerHelper.cs
  src/Agent.Worker/Handlers/ProcessHandler/ProcessHandlerV2.cs
  src/Common.props
  src/Test/L0/Worker/Handlers/CmdArgsSanitizerL0.cs
  src/Test/L0/Worker/Handlers/ProcessHandlerHelperL0.cs
  src/Test/L0/Worker/Handlers/ProcessHandlerHelperTelemetryL0.cs
  src/Test/L0/Worker/Handlers/ProcessHandlerL0.cs
Labels: internal

#4750 Removed FF calls causing instability in during VMSS configuration
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/Configuration/IRSAKeyManager.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
Labels: bug

#4755 Update README.md: Latest and pre-release labels information
  README.md
Labels: internal

#4744 Add the ability to modify SIGINT and SIGTERM timeouts and use graceful shutdown for worker child processes
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/ProcessInvoker.cs
  src/Agent.Worker/Handlers/NodeHandler.cs
  src/Agent.Worker/Handlers/PowerShell3Handler.cs
  src/Agent.Worker/Handlers/ProcessHandler/ProcessHandler.cs
  src/Agent.Worker/Handlers/ProcessHandler/ProcessHandlerV2.cs
  src/Agent.Worker/Handlers/StepHost.cs
  src/Microsoft.VisualStudio.Services.Agent/ProcessInvoker.cs
Labels: enhancement, Area: Agent

#4760 Cancel chcp 65001 configuration by timeout
  src/Agent.Worker/StepsRunner.cs
Labels: enhancement

#4754 Build the agent `linux-musl-arm64`
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
  assets.json
  releaseNote.md
  src/Agent.Worker/JobExtension.cs
  src/Common.props
  src/Misc/InstallAgentPackage.template.xml
  src/Misc/Publish.template.ps1
  src/Misc/externals.sh
  src/Test/L0/ConstantGenerationL0.cs
  src/dev.sh
Labels: enhancement

#4769 Update Git to v2.44.0
  src/Misc/externals.sh
Labels: internal

#4779 Handling disposed connection
  src/Agent.Worker/TestResults/Legacy/LegacyTestRunDataPublisher.cs
  src/Agent.Worker/TestResults/TestDataPublisher.cs
Labels: bug, Area: Test
