Repository microsoft/azure-pipelines-agent, pull requests merged in 2024-11, with the labels that each got.

#5027 Fix agent hangs if agent fails to get FF state
  src/Agent.Listener/Configuration/FeatureFlagProvider.cs
Labels: bug, Area: Agent

#5026 Bump git to 2.47.0.2
  src/Misc/externals.sh
Labels: bug

#5038 Add lint & lint-verify commands
  .editorconfig
  src/Common.props
  src/dev.sh
Labels: internal

#5036 Add support for AzureLinux 3 to installdependencies
  src/Misc/layoutbin/installdependencies.sh
Labels: enhancement

#5030 Mask base64 values of secrets in pipeline logs
  src/Agent.Worker/Worker.cs
Labels: enhancement

#5021 [Agent] Support for Windows ARM 64 - AB#2143637
  .azure-pipelines/build-job.yml
  .azure-pipelines/pipeline.yml
  README.md
  assets.json
  releaseNote.md
  src/Common.props
  src/Misc/InstallAgentPackage.template.xml
  src/Misc/Publish.template.ps1
  src/Misc/UpdateAgentPackage.template.xml
  src/Misc/externals.sh
  src/Test/L0/ConstantGenerationL0.cs
  src/dev.sh
  src/dir.proj
Labels: enhancement

#5046 [Agent] CI Trigger for Windows ARM 64 - AB#2143637
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
Labels: enhancement

#5039 Fix connection getting disposed
  src/Agent.Worker/TestResults/Legacy/LegacyTestRunDataPublisher.cs
  src/Agent.Worker/TestResults/TestDataPublisher.cs
Labels: bug

#5049 [Agent] Bug Fix - Fixed Processor Arch Detection in Windows - AB#2232751
  README.md
  src/dev.sh
Labels: bug
