Repository microsoft/azure-pipelines-agent, pull requests merged in 2024-09, with the labels that each got.

#4968 Bump node version
  src/Misc/externals.sh
Labels: bug

#4955 Update tf.exe
  src/Agent.Plugins/TFCliManager.cs
  src/Agent.Plugins/TfsVCSourceProvider.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/TFCommandManager.cs
  src/Agent.Worker/Build/TfsVCSourceProvider.cs
  src/Agent.Worker/Handlers/LegacyPowerShellHandler.cs
  src/Agent.Worker/JobExtension.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/Release/ReleaseJobExtension.cs
  src/Agent.Worker/TfManager.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Misc/externals.sh
  src/Test/L0/ServiceInterfacesL0.cs
  src/Test/L0/TestHostContext.cs
  src/Test/L0/Worker/TfManagerL0.cs
Labels: internal

#4973 Add libicu74 to `installdependencies.sh` to account for Ubuntu 24
  src/Misc/layoutbin/installdependencies.sh
Labels: misc, dependencies

#4945 Add telemetry publisher about Knob values per Job request
  src/Agent.Worker/JobExtension.cs
Labels: misc, Area: ABTT

#4975 run AzurePowershell task using pwsh to prevent stackoverflow
  .vsts.release.yml
Labels: internal

#4977 Fix pathes in agent publish step
  .vsts.release.yml
Labels: internal

#4904 Update lint rules
  .editorconfig
Labels: internal

#4974 Parser changes for test results
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Worker/TestResults/Parser.cs
  src/Agent.Worker/TestResults/Utils/TestResultsConstants.cs
  src/Common.props
Labels: enhancement, Area: Test

#4943 Add .NET 8 target framework for building the agent
  .azure-pipelines/build-job.yml
  .azure-pipelines/build-jobs.yml
  .azure-pipelines/pipeline.yml
  .vsts.release.yml
  src/Agent.Listener/ValidationHelper/VerificationException.cs
  src/Common.props
  src/dev.sh
  src/dir.proj
Labels: enhancement, Area: Agent

#4983 Fix the release pipeline
  .vsts.release.yml
Labels: bug, Area: Release

#4985 Revert "Update tf.exe (#4955)"
  src/Agent.Plugins/TFCliManager.cs
  src/Agent.Plugins/TfsVCSourceProvider.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/TFCommandManager.cs
  src/Agent.Worker/Build/TfsVCSourceProvider.cs
  src/Agent.Worker/Handlers/LegacyPowerShellHandler.cs
  src/Agent.Worker/JobExtension.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/Release/ReleaseJobExtension.cs
  src/Agent.Worker/TfManager.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Misc/externals.sh
  src/Test/L0/ServiceInterfacesL0.cs
  src/Test/L0/TestHostContext.cs
  src/Test/L0/Worker/TfManagerL0.cs
Labels: internal

#4990 Update `TF.exe` and binding redirects for `vstshost`
  src/Agent.Plugins/TFCliManager.cs
  src/Agent.Plugins/TfsVCSourceProvider.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/TFCommandManager.cs
  src/Agent.Worker/Build/TfsVCSourceProvider.cs
  src/Agent.Worker/Handlers/LegacyPowerShellHandler.cs
  src/Agent.Worker/JobExtension.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/Release/ReleaseJobExtension.cs
  src/Agent.Worker/TfManager.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Misc/externals.sh
  src/Test/L0/ServiceInterfacesL0.cs
  src/Test/L0/TestHostContext.cs
  src/Test/L0/Worker/TfManagerL0.cs
Labels: internal

#4986 Add AlmaLinux to the list of supported OS for .NET 8
  src/Agent.Listener/net8.json
Labels: bug, Area: Agent

#4980 re-add net6.json for vsts extension compat
  src/Agent.Listener/net6.json
Labels: misc

#4965 Add the credential environment configuration to the Git checkout command
  src/Agent.Plugins/GitCliManager.cs
  src/Agent.Plugins/GitSourceProvider.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
Labels: bug

#4996 Add System.Security.Cryptography.Xml package to fix CVE-2022-34716
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
Labels: bug, Area: Agent

#4991 Added reauth command to refresh existing agent credentials
  src/Agent.Listener/Agent.cs
  src/Agent.Listener/CommandLine/ReAuthAgent.cs
  src/Agent.Listener/CommandSettings.cs
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Agent.Listener/Program.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Misc/layoutroot/reauth.cmd
  src/Misc/layoutroot/reauth.sh
  src/Test/L0/Listener/CommandSettingsL0.cs
Labels: misc

#4987 Fallback from Node 20 to Node 16 on container startup
  src/Agent.Sdk/ContainerInfo.cs
  src/Agent.Sdk/ExecutionTargetInfo.cs
  src/Agent.Worker/Container/DockerCommandManager.cs
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Agent.Worker/Handlers/StepHost.cs
  src/Misc/layoutbin/containerHandlerInvoker.js.template
Labels: misc

#4995 Add script for checking if agents support upgrade to v4
  tools/FindAgentsNotCompatibleWithAgent/QueryAgentPoolsForCompatibleOS.ps1
Labels: misc

#5003 Rename FF `CheckIfTaskNodeRunnerIsDeprecated`
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/TaskManager.cs
Labels: misc
