Repository microsoft/azure-pipelines-agent, pull requests merged in 2024-05, with the labels that each got.

#4776 Resolve NuGet vulnerabilities for System.Data.SqlClient
  src/Agent.PluginHost/Agent.PluginHost.csproj
  src/Agent.Sdk/Agent.Sdk.csproj
Labels: bug

#4745 [GHSA-vh55-786g-wjwj ] Bump System.Security.Cryptography.Xml to 6.0.7 and dotnet to 6.0.29
  .azure-pipelines/build-job.yml
  src/Common.props
  src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj
  src/dev.sh
Labels: bug

#4786 Allow publish execution handler telemetry for non in-the-box tasks
  src/Agent.Worker/TaskRunner.cs
  src/Test/L0/NodeHandlerL0.cs
  src/Test/L1/Worker/L1TestBase.cs
Labels: internal

#4795 Support container jobs running with ACR docker registry service connection with workload identity federation auth scheme
  src/Agent.Worker/ContainerOperationProvider.cs
  src/Agent.Worker/Variables.cs
Labels: enhancement, Area: Release, Containers

#4773 Update pipelines-* packages md
  docs/node6.md
Labels: internal

#4798 Update information about node runners in generated release notes
  releaseNote.md
Labels: internal

#4792 Updated to support Xamarin detection with VS2022
  src/Misc/layoutbin/powershell/Add-XamarinAndroidCapabilities.ps1
Labels: enhancement

#4791 Add -prerelease flag to lookup vsbuildtools in VisualStudioFunctions.ps1
  src/Misc/layoutbin/powershell/CapabilityHelpers/VisualStudioFunctions.ps1
Labels: enhancement

#4796 Add updating UpdateAgentPackage.xml in Release CI
  release/createAdoPrs.js
  src/Misc/UpdateAgentPackage.template.xml
Labels: internal

#4753 Ubuntu libssl package version does not exist any more in installdependencies.sh
  src/Misc/layoutbin/installdependencies.sh
Labels: bug

#4808 Users/dergacheve/migrate to esrp v5
  .azure-pipelines/signing.yml
Labels: internal

#4789 Add git telemetry to job runner
  src/Agent.Worker/JobExtension.cs
  src/Agent.Worker/JobRunner.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
Labels: enhancement

#4816 Revert "Update Git to v2.44.0 (#4769)"
  src/Misc/externals.sh
Labels: internal

#4823 Add skipBuildTagsForGitHubPullRequests parameter in the pipeline
  .azure-pipelines/pipeline.yml
Labels: internal

#4809 Changes to add tracelog for Featureflag exceptions
  src/Agent.Worker/TestResults/Utils/FeatureFlagService.cs
Labels: bug, Area: Test, DevOps
