Repository microsoft/azure-pipelines-agent, pull requests merged in 2025-09, with the labels that each got.

#5303 Form-data cgfix in release folder
  release/package-lock.json
Labels: bug

#5300 Adding process id in process invoker logs
  src/Agent.Sdk/ProcessInvoker.cs
Labels: enhancement

#5307 Adding code for duration tracking in lgos
  src/Agent.Listener/Agent.cs
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/StepsRunner.cs
  src/Agent.Worker/TaskRunner.cs
  src/Agent.Worker/Worker.cs
  src/Microsoft.VisualStudio.Services.Agent/EnhancedTracing.cs
  src/Microsoft.VisualStudio.Services.Agent/Tracing.cs
  src/Microsoft.VisualStudio.Services.Agent/TracingProxy.cs
Labels: enhancement

#5317 Misc changes to fix release pipeline
  .github/copilot-instructions.md
  .vsts.release.yml
  release/package-lock.json
  src/Common.props
  src/dev.sh
Labels: internal

#5302 Adding Unit Tests for Docker Start Retry Logic
  src/Test/L0/Container/DockerCommandManagerL0.cs
Labels: Area: Test, internal

#5314 Updated logic to flush logs when worker is stuck in long running jobs
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/JobRunner.cs
  src/Agent.Worker/StepsRunner.cs
  src/Agent.Worker/Worker.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Microsoft.VisualStudio.Services.Agent/HostTraceListener.cs
  src/Microsoft.VisualStudio.Services.Agent/Logging.cs
  src/Microsoft.VisualStudio.Services.Agent/ProcessChannel.cs
  src/Microsoft.VisualStudio.Services.Agent/TraceManager.cs
  src/Microsoft.VisualStudio.Services.Agent/TracingProxy.cs
  src/Test/L0/Container/DockerCommandManagerL0.cs
  src/Test/L0/EnhancedTracingL0.cs
  src/Test/L0/Listener/JobDispatcherL0.cs
  src/Test/L0/TestHostContext.cs
  src/Test/L0/Worker/StepsRunnerL0.cs
  src/Test/L0/Worker/WorkerL0.cs
  src/Test/L1/Worker/TimeoutLogFlushingL1Tests.cs
Labels: enhancement

#5327 Ensure safe access to _proc in ProcessInvoker
  src/Agent.Sdk/ProcessInvoker.cs
Labels: enhancement

#5332 Fixed test cases for job timeout
  src/Test/L1/Worker/L1TestBase.cs
Labels: misc
