Repository microsoft/azure-pipelines-agent, pull requests merged in 2025-02, with the labels that each got.

#5085 Added WIF support for checkout task
  src/Agent.Plugins/GitSourceProvider.cs
  src/Test/L0/Plugin/TestGitSourceProvider/GitSourceProviderL0.cs
  src/Test/L0/Plugin/TestGitSourceProvider/MockAgentTaskPluginExecutionContext.cs
  src/Test/L0/Plugin/TestGitSourceProvider/MockGitCliManager.cs
  src/Test/L0/Plugin/TestGitSourceProvider/MockGitSoureProvider.cs
Labels: enhancement

#5102 Adding registry key for VS telemetry to identify if Agent is installed on the same machine as VS
  src/Agent.Listener/Configuration/ConfigurationManager.cs
Labels: misc

#5106 [Checkout] Configure sparse checkouts before fetch
  src/Agent.Plugins/GitSourceProvider.cs
Labels: bug

#5109 Increase timeout for artifact associate for pipeline artifact
  src/Agent.Plugins/Artifact/BuildServer.cs
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/Build/BuildServer.cs
Labels: enhancement

#5112 Update ADO Client package to 251
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Worker/Release/Artifacts/CustomArtifact.cs
  src/Agent.Worker/TestResults/Parser.cs
  src/Common.props
Labels: misc, dependencies

#5117 Check git version before running sparse checkout
  src/Agent.Plugins/GitSourceProvider.cs
Labels: misc

#5115 Fix L1 test failures by upgrading nuget version
  src/Misc/externals.sh
  src/dev.sh
Labels: Area: Test, internal

#5118 Updated Node 20 version to safe version
  src/Misc/externals.sh
Labels: enhancement

#5116 Changes to skip Not Executed state test in result.publish() command
  src/Agent.Worker/TestResults/TestDataPublisher.cs
Labels: enhancement, Area: Test

#5122 Suppressing CodeQL [SM02196] warning
  src/Agent.Worker/Build/TrackingConfigHashAlgorithm.cs
Labels: bug

#5125 Custom tasks that use Node 16 runner version should emit a warning
  src/Agent.Worker/TaskManager.cs
Labels: enhancement

#5129 Disabling Scheduled Run as we do manual release builds.
  .vsts.release.yml
Labels: internal

#5131 Remove unused maxParallelism parameter from CreateDedupManifestClientAsync
  src/Agent.Plugins/Artifact/FileShareProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactProvider.cs
  src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
Labels: misc

#5130 Adding PR Template
  .github/pull_request_template.md
Labels: internal
