Repository microsoft/azure-pipelines-agent, pull requests merged in 2025-01, with the labels that each got.

#5084 Create .CodeQL.yml
  .CodeQL.yml
Labels: misc

#5080 Disable Windows ARM64 from the release pipeline and notes
  .azure-pipelines/pipeline.yml
  .vsts.ci.yml
  releaseNote.md
Labels: misc

#5089 [Agent][Edgio] Remove Azure CDN Cache Commands to Unblock Pipeline Failures Due to Edgio Retirement - AB#2242851
  .vsts.release.yml
Labels: bug

#5093 Upgrade runner image in pipeline from macos-12 to macos-14
  .azure-pipelines/pipeline.yml
Labels: misc

#5092 FIX: Tasks on MacOS agents not completing but marked as succeeded.
  src/Agent.Sdk/ProcessInvoker.cs
  src/Agent.Worker/ResourceMetricsManager.cs
Labels: bug

#5068 FIX: [CodeQL: SM02184] Server certificate validation disabled in VssUtil.cs
  src/Agent.Sdk/Util/VssUtil.cs
  src/Test/L0/Util/VssUtilL0.cs
Labels: bug

#5096 Migrated signing
  .azure-pipelines/signing.yml
Labels: internal
