Repository microsoft/azure-pipelines-agent, pull requests merged in 2025-04, with the labels that each got.

#5163 Fix indentation in secret masking files
  src/Agent.Sdk/SecretMasking/SecretMasker.cs
  src/Test/L0/SecretMaskerTests/SecretMaskerL0.cs
Labels: misc

#5167 Agent CDN - devAzure - Replaced azureedge.net references in GitHub Release Template - AB#2241315
  assets.json
  releaseNote.md
Labels: internal

#5169 Use Microsoft.Security.Utilities.Core package for the 'new' secret masker
  src/Agent.Listener/JobDispatcher.cs
  src/Agent.Sdk/Agent.Sdk.csproj
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/SecretMasking/ILoggedSecretMasker.cs
  src/Agent.Sdk/SecretMasking/ISecret.cs
  src/Agent.Sdk/SecretMasking/ISecretMasker.cs
  src/Agent.Sdk/SecretMasking/LegacyLoggedSecretMasker.cs
  src/Agent.Sdk/SecretMasking/LoggedSecretMasker.cs
  src/Agent.Sdk/SecretMasking/OssSecretMasker.cs
  src/Agent.Sdk/SecretMasking/RegexSecret.cs
  src/Agent.Sdk/SecretMasking/ReplacementPosition.cs
  src/Agent.Sdk/SecretMasking/SecretMasker.cs
  src/Agent.Sdk/SecretMasking/ValueSecret.cs
  src/Agent.Sdk/Util/WellKnownSecretAliases.cs
  src/Agent.Worker/Worker.cs
  src/Microsoft.VisualStudio.Services.Agent/AdditionalMaskingRegexes.CredScan.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Microsoft.VisualStudio.Services.Agent/HostContext.cs
  src/Microsoft.VisualStudio.Services.Agent/TraceManager.cs
  src/Microsoft.VisualStudio.Services.Agent/Tracing.cs
  src/Test/L0/HostContextL0.cs
  src/Test/L0/SecretMaskerTests/LoggedSecretMaskerL0.cs
  src/Test/L0/SecretMaskerTests/RegexSecretL0.cs
  src/Test/L0/SecretMaskerTests/SecretMaskerL0.cs
  src/Test/L0/TestHostContext.cs
  tools/CredScanRegexes/CredScanPatternExtractor.cs
  tools/CredScanRegexes/CredScanRegexes.csproj
  tools/CredScanRegexes/PatternProcessor.cs
  tools/CredScanRegexes/Program.cs
  tools/CredScanRegexes/nuget.config
  tools/CredScanRegexes/readme.md
Labels: enhancement

#5175 Updated Agent code to handling '+' sign in file path for build configs
  src/Agent.Worker/TaskManager.cs
  src/Microsoft.VisualStudio.Services.Agent/TaskServer.cs
Labels: enhancement, Area: ABTT

#5184 Prevent using vso commands with Build.SourceVersionAuthor variable
  src/Agent.Worker/Variables.cs
  src/Microsoft.VisualStudio.Services.Agent/Constants.cs
  src/Test/L0/Worker/WorkerL0.cs
Labels: enhancement

#5182 Fix duplication of commit descriptions and missing PRs in release notes.
  .vsts.release.yml
  release/createReleaseBranch.js
  release/package-lock.json
  release/package.json
Labels: internal

#5190 updating package lock for newly added dependencies
  release/package-lock.json
Labels: internal
