Repository microsoft/azure-pipelines-agent, pull requests merged in 2025-03, with the labels that each got.

#5132 Optionally use max parallelism value from the client settings API
  src/Agent.Plugins/Artifact/FileContainerProvider.cs
  src/Agent.Plugins/Artifact/PipelineArtifactServer.cs
  src/Agent.Worker/Build/FileContainerServer.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/BlobstoreClientSettings.cs
  src/Microsoft.VisualStudio.Services.Agent/Blob/DedupManifestArtifactClientFactory.cs
  src/Microsoft.VisualStudio.Services.Agent/JobServer.cs
  src/Test/L0/Plugin/TestFileShareProvider/MockDedupManifestArtifactClientFactory.cs
Labels: enhancement

#5148 add Ubuntu 20 to the list of deprecated iamges
  tools/FindPipelinesUsingRetiredImages/QueryJobHistoryForRetiredImages.ps1
Labels: misc

#5144 Skip removing read only attribute for Symlinks AB#2248480
  src/Agent.Sdk/Util/IOUtil.cs
  src/Test/L0/Util/IOUtilL0.cs
Labels: bug, Area: Agent
