Repository microsoft/azure-pipelines-agent, pull requests merged in 2025-05, with the labels that each got.

#5191 add windows 2019 to the script checking for jobs with retired images
  tools/FindPipelinesUsingRetiredImages/QueryJobHistoryForRetiredImages.ps1
Labels: internal

#5194 [Agent] Improved PR Template
  .github/pull_request_template.md
Labels: internal

#5193 updating nodejs version in release template
  .vsts.release.yml
Labels: internal

#5158 Deactivate Base64 Encoded Vso Commands AB#2008236
  src/Agent.Sdk/Util/StringUtil.cs
  src/Test/L0/Util/StringUtilL0.cs
  src/Test/L0/Worker/WorkerL0.cs
Labels: misc

#5197 Agent CDN - devAzure - Updated CDN URL in Servicing Templates - AB#2241315
  src/Misc/InstallAgentPackage.template.xml
  src/Misc/Publish.template.ps1
  src/Misc/UpdateAgentPackage.template.xml
Labels: internal

#5196 Update QueryJobHistoryForRetiredImages.ps1
  tools/FindPipelinesUsingRetiredImages/QueryJobHistoryForRetiredImages.ps1
Labels: internal

#5138 Upgrate new version of tf.exe - vstsom.zip - AB#2257240
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/TfManager.cs
  src/Misc/externals.sh
  src/Test/L0/Worker/TfManagerL0.cs
Labels: internal

#5201 Agent Release - Replaced Download .NET Vanity URL with Actual URL
  src/dev.sh
Labels: misc

#5202 Agent CDN - Added Warning in Initialize Phase when new Agent CDN is not reachable - AB#2241315
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Sdk/Util/PlatformUtil.cs
  src/Agent.Worker/JobExtension.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: internal

#5207 Fixes Release notes issue.
  .vsts.release.yml
  release/createReleaseBranch.js
Labels: internal

#5217 Revert "Upgrate new version of tf.exe - vstsom.zip - AB#2257240 (#5138)"
  src/Agent.Sdk/Knob/AgentKnobs.cs
  src/Agent.Worker/TfManager.cs
  src/Misc/externals.sh
  src/Test/L0/Worker/TfManagerL0.cs
Labels: misc

#5210 Handle TimeoutException During Agent Replacement in agent configuration
  src/Agent.Listener/Configuration/ConfigurationManager.cs
  src/Misc/layoutbin/en-US/strings.json
Labels: bug
